"""
Django settings for p_tienda project.

Generated by 'django-admin startproject' using Django 5.2.5.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path
import os # ---------------------- Buscar qué hace

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-vnxk=l0_txql@ge6b^6bs3225cx1k)v%+6)-w7%@vf_ilu_pr@'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'a_login',
    'a_inicio',
    'a_central',
    'a_cajas',
    'a_compras',
    'a_stock',
    'a_ventas',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'p_tienda.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, 'templates')],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request', # Esto permite usar request en templates
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'p_tienda.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = { # Configuración de la BD
    'default': {
        'ENGINE': 'django.db.backends.mysql',
        'NAME': 'kiosco_mateo',
        'USER': 'root',
        'PASSWORD': 'root',
        'HOST': 'localhost',
        'PORT': '3306',
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'America/Argentina/Buenos_Aires' # Para utilizar la zona horaria de Argentina

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = '/static/'

# Directorio base del proyecto
BASE_DIR = Path(__file__).resolve().parent.parent

# Ruta completa para el directorio de archivos estáticos del proyecto
STATIC_ROOT = os.path.join(BASE_DIR, 'static_root')



# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

LOGIN_URL = '/cuenta/login/'

LOGIN_REDIRECT_URL = 'a_inicio:inicio'

LOGOUT_REDIRECT_URL = 'a_login:login'

# =========================================================
# CONFIGURACIÓN DE CORREO ELECTRÓNICO (SMTP - GMAIL)
# =========================================================
EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = 'smtp.gmail.com' # Para Gmail
EMAIL_PORT = 587 # Puerto estándar para TLS
EMAIL_USE_TLS = True # Usar Transport Layer Security (recomendado)
EMAIL_TIMEOUT = 5

# Credenciales de tu cuenta de correo
# Usar variables de entorno (os.environ) en producción es la MEJOR práctica
EMAIL_HOST_USER = 'kiosco.mateo.2025@gmail.com'  # E-mail emisor
EMAIL_HOST_PASSWORD = 'jkmgzbkpixrokgfh' # Contraseña de Aplicación/App Password del E-mail emisor

# Email que aparecerá como remitente
DEFAULT_FROM_EMAIL = 'Mi Tienda Mateo - Soporte <kiosco.mateo.2025@gmail.com>'