# Generated by Django 5.2.5 on 2025-11-28 17:44

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('a_central', '0006_productos_cantidad_por_pack_productos_tipo_unidad'),
    ]

    operations = [
        migrations.CreateModel(
            name='LoteProducto',
            fields=[
                ('id_lote', models.AutoField(primary_key=True, serialize=False)),
                ('numero_lote', models.CharField(editable=False, max_length=30, unique=True)),
                ('cantidad', models.PositiveIntegerField()),
                ('fecha_ingreso', models.DateField(default=django.utils.timezone.now)),
                ('fecha_vencimiento', models.DateField()),
                ('activo', models.BooleanField(default=True)),
                ('borrado_logico', models.BooleanField(default=False)),
                ('id_loc_com', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='a_central.localescomerciales')),
                ('id_producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='a_central.productos')),
            ],
            options={
                'verbose_name_plural': 'Lotes de Productos',
                'db_table': 'Lotes_Productos',
            },
        ),
        migrations.CreateModel(
            name='ObservacionStock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('producto_id', models.CharField(max_length=100)),
                ('motivo', models.CharField(max_length=50)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('fecha', models.DateField()),
                ('cantidad', models.PositiveIntegerField()),
                ('lote', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='a_stock.loteproducto')),
            ],
        ),
        migrations.CreateModel(
            name='Proveedoresxloccom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fh_ultima_visita', models.DateTimeField(blank=True, db_column='FH_Ultima_Visita', null=True)),
                ('borrado_pxlc', models.BooleanField(db_column='Borrado_PxLC', default=False)),
                ('fh_borrado_pxlc', models.DateTimeField(blank=True, db_column='FH_Borrado_PxLC', null=True)),
                ('id_loc_com', models.ForeignKey(db_column='ID_Loc_Com', on_delete=django.db.models.deletion.DO_NOTHING, to='a_central.localescomerciales')),
                ('id_proveedor', models.ForeignKey(db_column='ID_Proveedor', on_delete=django.db.models.deletion.DO_NOTHING, to='a_central.proveedores')),
            ],
            options={
                'verbose_name_plural': 'Proveedores por Local Comercial',
                'db_table': 'ProveedoresXLocCom',
                'unique_together': {('id_proveedor', 'id_loc_com')},
            },
        ),
        migrations.CreateModel(
            name='Proveedoresxproductos',
            fields=[
                ('id_prov_prod', models.AutoField(db_column='ID_Prov_Prod', primary_key=True, serialize=False)),
                ('costo_compra', models.DecimalField(blank=True, db_column='Costo_Compra', decimal_places=2, max_digits=10, null=True)),
                ('borrado_pvxpr', models.BooleanField(db_column='Borrado_PvXPr', default=False)),
                ('fh_borrado_pvxpr', models.DateTimeField(blank=True, db_column='FH_Borrado_PvXPr', null=True)),
                ('id_producto', models.ForeignKey(db_column='ID_Producto', on_delete=django.db.models.deletion.DO_NOTHING, to='a_central.productos')),
                ('id_proveedor', models.ForeignKey(db_column='ID_Proveedor', on_delete=django.db.models.deletion.DO_NOTHING, to='a_central.proveedores')),
            ],
            options={
                'verbose_name_plural': 'Proveedores por Productos',
                'db_table': 'ProveedoresXProductos',
                'unique_together': {('id_proveedor', 'id_producto')},
            },
        ),
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id_stock_sucursal', models.AutoField(db_column='ID_Stock_Sucursal', primary_key=True, serialize=False)),
                ('stock_pxlc', models.IntegerField(db_column='Stock_PxLC')),
                ('stock_min_pxlc', models.IntegerField(db_column='Stock_Min_PxLC')),
                ('borrado_pxlc', models.BooleanField(db_column='Borrado_PxLC', default=False)),
                ('fh_borrado_pxlc', models.DateTimeField(blank=True, db_column='FH_Borrado_PxLC', null=True)),
                ('id_loc_com', models.ForeignKey(db_column='ID_Loc_Com', on_delete=django.db.models.deletion.DO_NOTHING, to='a_central.localescomerciales')),
                ('id_producto', models.ForeignKey(db_column='ID_Producto', on_delete=django.db.models.deletion.DO_NOTHING, to='a_central.productos')),
            ],
            options={
                'verbose_name_plural': 'Stock por Local Comercial',
                'db_table': 'Stock',
                'unique_together': {('id_producto', 'id_loc_com')},
            },
        ),
    ]
