# Generated by Django 5.2.5 on 2025-09-13 23:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('a_central', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Marcas',
            fields=[
                ('id_marca', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_marca', models.CharField(max_length=120, unique=True)),
                ('borrado_logico', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name_plural': 'Marcas',
                'db_table': 'Marcas',
            },
        ),
        migrations.CreateModel(
            name='Proveedores',
            fields=[
                ('cuit_proveedor', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('nombre_proveedor', models.CharField(max_length=160)),
                ('telefono_proveedor', models.CharField(blank=True, max_length=30, null=True)),
                ('email_proveedor', models.CharField(blank=True, max_length=150, null=True)),
                ('direccion_proveedor', models.CharField(blank=True, max_length=200, null=True)),
                ('habilitado_proveedor', models.BooleanField(default=True)),
                ('borrado_logico', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name_plural': 'Proveedores',
                'db_table': 'Proveedores',
            },
        ),
        migrations.CreateModel(
            name='Productos',
            fields=[
                ('id_producto', models.BigAutoField(primary_key=True, serialize=False)),
                ('descripcion_producto', models.CharField(max_length=200)),
                ('precio_unitario_venta', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('fecha_elaboracion', models.DateField(blank=True, null=True)),
                ('fecha_vencimiento', models.DateField(blank=True, null=True)),
                ('borrado_logico', models.BooleanField(default=False)),
                ('id_marca', models.ForeignKey(blank=True, db_column='id_marca', null=True, on_delete=django.db.models.deletion.SET_NULL, to='a_stock.marcas')),
            ],
            options={
                'verbose_name_plural': 'Productos',
                'db_table': 'Productos',
            },
        ),
        migrations.CreateModel(
            name='ProveedoresProductos',
            fields=[
                ('id_proveedor_producto', models.BigAutoField(primary_key=True, serialize=False)),
                ('precio_proveedor', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('borrado_logico', models.BooleanField(default=False)),
                ('cuit_proveedor', models.ForeignKey(db_column='cuit_proveedor', on_delete=django.db.models.deletion.CASCADE, to='a_stock.proveedores')),
                ('id_producto', models.ForeignKey(db_column='id_producto', on_delete=django.db.models.deletion.CASCADE, to='a_stock.productos')),
            ],
            options={
                'verbose_name_plural': 'Proveedores de Productos',
                'db_table': 'Proveedores_Productos',
                'unique_together': {('cuit_proveedor', 'id_producto')},
            },
        ),
        migrations.CreateModel(
            name='StocksSucursales',
            fields=[
                ('id_stock', models.BigAutoField(primary_key=True, serialize=False)),
                ('cantidad_stock', models.BigIntegerField(default=0)),
                ('borrado_logico', models.BooleanField(default=False)),
                ('id_producto', models.ForeignKey(db_column='id_producto', on_delete=django.db.models.deletion.CASCADE, to='a_stock.productos')),
                ('id_sucursal', models.ForeignKey(db_column='id_sucursal', on_delete=django.db.models.deletion.CASCADE, to='a_central.sucursales')),
            ],
            options={
                'verbose_name_plural': 'Stocks de Sucursales',
                'db_table': 'Stocks_Sucursales',
                'unique_together': {('id_producto', 'id_sucursal')},
            },
        ),
    ]
