# Generated by Django 5.2.5 on 2025-11-05 23:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('a_stock', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ObservacionStock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('producto', models.CharField(max_length=100)),
                ('motivo', models.CharField(max_length=200)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('fecha', models.DateField()),
                ('cantidad', models.PositiveIntegerField()),
            ],
        ),
    ]
