# Generated by Django 5.2.5 on 2025-09-30 13:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('a_central', '0004_billeterasvirtuales_marcas_proveedores_and_more'),
        ('a_compras', '0002_remove_compras_borrado_logico_and_more'),
        ('a_stock', '0001_initial'),
        ('a_ventas', '0002_remove_detallesventas_borrado_logico_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productos',
            name='id_marca',
        ),
        migrations.RemoveField(
            model_name='stockssucursales',
            name='id_producto',
        ),
        migrations.RemoveField(
            model_name='proveedoresproductos',
            name='id_producto',
        ),
        migrations.RemoveField(
            model_name='proveedoresproductos',
            name='cuit_proveedor',
        ),
        migrations.AlterUniqueTogether(
            name='proveedoresproductos',
            unique_together=None,
        ),
        migrations.AlterUniqueTogether(
            name='stockssucursales',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='stockssucursales',
            name='id_sucursal',
        ),
        migrations.CreateModel(
            name='Proveedoresxloccom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fh_ultima_visita', models.DateTimeField(blank=True, db_column='FH_Ultima_Visita', null=True)),
                ('borrado_pxlc', models.BooleanField(db_column='Borrado_PxLC', default=False)),
                ('fh_borrado_pxlc', models.DateTimeField(blank=True, db_column='FH_Borrado_PxLC', null=True)),
                ('id_loc_com', models.ForeignKey(db_column='ID_Loc_Com', on_delete=django.db.models.deletion.DO_NOTHING, to='a_central.localescomerciales')),
                ('id_proveedor', models.ForeignKey(db_column='ID_Proveedor', on_delete=django.db.models.deletion.DO_NOTHING, to='a_central.proveedores')),
            ],
            options={
                'verbose_name_plural': 'Proveedores por Local Comercial',
                'db_table': 'ProveedoresXLocCom',
                'unique_together': {('id_proveedor', 'id_loc_com')},
            },
        ),
        migrations.CreateModel(
            name='Proveedoresxproductos',
            fields=[
                ('id_prov_prod', models.AutoField(db_column='ID_Prov_Prod', primary_key=True, serialize=False)),
                ('costo_compra', models.DecimalField(blank=True, db_column='Costo_Compra', decimal_places=2, max_digits=10, null=True)),
                ('borrado_pvxpr', models.BooleanField(db_column='Borrado_PvXPr', default=False)),
                ('fh_borrado_pvxpr', models.DateTimeField(blank=True, db_column='FH_Borrado_PvXPr', null=True)),
                ('id_producto', models.ForeignKey(db_column='ID_Producto', on_delete=django.db.models.deletion.DO_NOTHING, to='a_central.productos')),
                ('id_proveedor', models.ForeignKey(db_column='ID_Proveedor', on_delete=django.db.models.deletion.DO_NOTHING, to='a_central.proveedores')),
            ],
            options={
                'verbose_name_plural': 'Proveedores por Productos',
                'db_table': 'ProveedoresXProductos',
                'unique_together': {('id_proveedor', 'id_producto')},
            },
        ),
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id_stock_sucursal', models.AutoField(db_column='ID_Stock_Sucursal', primary_key=True, serialize=False)),
                ('stock_pxlc', models.IntegerField(db_column='Stock_PxLC')),
                ('stock_min_pxlc', models.IntegerField(db_column='Stock_Min_PxLC')),
                ('borrado_pxlc', models.BooleanField(db_column='Borrado_PxLC', default=False)),
                ('fh_borrado_pxlc', models.DateTimeField(blank=True, db_column='FH_Borrado_PxLC', null=True)),
                ('id_loc_com', models.ForeignKey(db_column='ID_Loc_Com', on_delete=django.db.models.deletion.DO_NOTHING, to='a_central.localescomerciales')),
                ('id_producto', models.ForeignKey(db_column='ID_Producto', on_delete=django.db.models.deletion.DO_NOTHING, to='a_central.productos')),
            ],
            options={
                'verbose_name_plural': 'Stock por Local Comercial',
                'db_table': 'Stock',
                'unique_together': {('id_producto', 'id_loc_com')},
            },
        ),
        migrations.DeleteModel(
            name='Marcas',
        ),
        migrations.DeleteModel(
            name='Productos',
        ),
        migrations.DeleteModel(
            name='Proveedores',
        ),
        migrations.DeleteModel(
            name='ProveedoresProductos',
        ),
        migrations.DeleteModel(
            name='StocksSucursales',
        ),
    ]
