# Generated by Django 5.2.5 on 2025-11-07 15:56

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('a_central', '0005_alter_billeterasvirtuales_fh_alta_bv_and_more'),
        ('a_stock', '0002_observacionstock'),
    ]

    operations = [
        migrations.CreateModel(
            name='LoteProducto',
            fields=[
                ('id_lote', models.AutoField(primary_key=True, serialize=False)),
                ('numero_lote', models.CharField(editable=False, max_length=30, unique=True)),
                ('cantidad', models.PositiveIntegerField()),
                ('fecha_ingreso', models.DateField(default=django.utils.timezone.now)),
                ('fecha_vencimiento', models.DateField()),
                ('activo', models.BooleanField(default=True)),
                ('id_loc_com', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='a_central.localescomerciales')),
                ('id_producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='a_central.productos')),
            ],
            options={
                'verbose_name_plural': 'Lotes de Productos',
                'db_table': 'Lotes_Productos',
            },
        ),
    ]
