# Generated by Django 5.2.5 on 2025-11-08 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('a_stock', '0003_loteproducto'),
    ]

    operations = [
        migrations.AddField(
            model_name='loteproducto',
            name='borrado_logico',
            field=models.BooleanField(default=False),
        ),
    ]
