# Generated by Django 5.2.5 on 2025-11-26 23:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('a_central', '0006_productos_cantidad_por_pack_productos_tipo_unidad'),
        ('a_stock', '0004_loteproducto_borrado_logico'),
    ]

    operations = [
        migrations.AlterField(
            model_name='observacionstock',
            name='motivo',
            field=models.CharField(choices=[('Pérdida', 'Pérdida'), ('Rotura', 'Rotura'), ('Vencimiento', 'Vencimiento'), ('Robo', 'Robo'), ('Otro', 'Otro')], max_length=50),
        ),
        migrations.AlterField(
            model_name='observacionstock',
            name='producto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='a_central.productos'),
        ),
    ]
