# Generated by Django 5.2.5 on 2025-11-27 00:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('a_stock', '0005_observacionstock_lote_alter_observacionstock_motivo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='observacionstock',
            name='lote',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='a_stock.loteproducto'),
        ),
        migrations.AlterField(
            model_name='observacionstock',
            name='motivo',
            field=models.CharField(max_length=200),
        ),
    ]
