# Generated by Django 5.2.5 on 2025-08-24 01:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('a_productos', '0001_initial'),
        ('a_sucursales', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PedidosProvisorios',
            fields=[
                ('id_pedprov', models.IntegerField(db_column='ID_Pedprov', primary_key=True, serialize=False)),
                ('cantidad_prov', models.IntegerField(blank=True, db_column='Cantidad_Prov', null=True)),
                ('total_costo', models.DecimalField(blank=True, db_column='Total_Costo', decimal_places=2, max_digits=10, null=True)),
            ],
            options={
                'db_table': 'Pedidos_Provisorios',
            },
        ),
        migrations.CreateModel(
            name='Proveedores',
            fields=[
                ('cuit_pv', models.IntegerField(db_column='Cuit_Pv', primary_key=True, serialize=False)),
                ('nombre_pv', models.CharField(blank=True, db_column='Nombre_Pv', max_length=50, null=True)),
                ('telefono_pv', models.CharField(blank=True, db_column='Telefono_Pv', max_length=50, null=True)),
                ('email_pv', models.CharField(blank=True, db_column='Email_Pv', max_length=100, null=True)),
                ('direccion_pv', models.CharField(blank=True, db_column='Direccion_Pv', max_length=100, null=True)),
                ('habilitado', models.CharField(blank=True, db_column='Habilitado', max_length=2, null=True)),
            ],
            options={
                'db_table': 'Proveedores',
            },
        ),
        migrations.CreateModel(
            name='PedidosConfirmados',
            fields=[
                ('id_pedconf', models.IntegerField(db_column='ID_PedConf', primary_key=True, serialize=False)),
                ('cuit_pv', models.ForeignKey(db_column='Cuit_Pv', on_delete=django.db.models.deletion.DO_NOTHING, to='a_proveedores.proveedores')),
            ],
            options={
                'db_table': 'Pedidos_Confirmados',
            },
        ),
        migrations.CreateModel(
            name='PedidosConfxproductos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('observaciones', models.CharField(blank=True, db_column='Observaciones', max_length=100, null=True)),
                ('id_pedconf', models.ForeignKey(db_column='ID_PedConf', on_delete=django.db.models.deletion.DO_NOTHING, to='a_proveedores.pedidosconfirmados')),
                ('id_productos', models.ForeignKey(db_column='ID_Productos', on_delete=django.db.models.deletion.DO_NOTHING, to='a_productos.productos')),
            ],
            options={
                'db_table': 'Pedidos_ConfXProductos',
                'unique_together': {('id_pedconf', 'id_productos')},
            },
        ),
        migrations.CreateModel(
            name='PedidosProvxproductos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(blank=True, db_column='Descripcion', max_length=100, null=True)),
                ('id_pedprov', models.ForeignKey(db_column='ID_Pedprov', on_delete=django.db.models.deletion.DO_NOTHING, to='a_proveedores.pedidosprovisorios')),
                ('id_productos', models.ForeignKey(db_column='ID_Productos', on_delete=django.db.models.deletion.DO_NOTHING, to='a_productos.productos')),
            ],
            options={
                'db_table': 'Pedidos_ProvXProductos',
                'unique_together': {('id_pedprov', 'id_productos')},
            },
        ),
        migrations.CreateModel(
            name='Proveedoresxloccom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_ultima_visita', models.DateField(blank=True, db_column='Fecha_Ultima_Visita', null=True)),
                ('hora_ultima_visita', models.TimeField(blank=True, db_column='Hora_Ultima_Visita', null=True)),
                ('cuit_pv', models.ForeignKey(db_column='Cuit_Pv', on_delete=django.db.models.deletion.DO_NOTHING, to='a_proveedores.proveedores')),
                ('id_loc_com', models.ForeignKey(db_column='ID_Loc_Com', on_delete=django.db.models.deletion.DO_NOTHING, to='a_sucursales.localescomerciales')),
            ],
            options={
                'db_table': 'ProveedoresXLocCom',
                'unique_together': {('cuit_pv', 'id_loc_com')},
            },
        ),
        migrations.CreateModel(
            name='Proveedoresxproductos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ultima_entrega', models.DateField(blank=True, db_column='Ultima_Entrega', null=True)),
                ('observacion', models.CharField(blank=True, db_column='Observacion', max_length=500, null=True)),
                ('cuit_pv', models.ForeignKey(db_column='Cuit_Pv', on_delete=django.db.models.deletion.DO_NOTHING, to='a_proveedores.proveedores')),
                ('id_productos', models.ForeignKey(db_column='ID_Productos', on_delete=django.db.models.deletion.DO_NOTHING, to='a_productos.productos')),
            ],
            options={
                'db_table': 'ProveedoresXProductos',
                'unique_together': {('cuit_pv', 'id_productos')},
            },
        ),
    ]
