# Generated by Django 5.2.5 on 2025-08-24 01:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('a_sucursales', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Empleados',
            fields=[
                ('legajo_nro', models.IntegerField(db_column='Legajo_Nro', primary_key=True, serialize=False)),
                ('dni_emp', models.CharField(db_column='Dni_Emp', max_length=20)),
                ('apellido_emp', models.CharField(blank=True, db_column='Apellido_Emp', max_length=50, null=True)),
                ('nombre_emp', models.CharField(blank=True, db_column='Nombre_Emp', max_length=50, null=True)),
                ('email_emp', models.CharField(blank=True, db_column='Email_Emp', max_length=100, null=True)),
                ('telefono_emp', models.CharField(blank=True, db_column='Telefono_Emp', max_length=50, null=True)),
                ('domicilio_emp', models.CharField(blank=True, db_column='Domicilio_Emp', max_length=100, null=True)),
                ('fecha_alta', models.DateTimeField(blank=True, db_column='Fecha_Alta', null=True)),
                ('fecha_baja', models.DateTimeField(blank=True, db_column='Fecha_Baja', null=True)),
            ],
            options={
                'db_table': 'Empleados',
            },
        ),
        migrations.CreateModel(
            name='Roles',
            fields=[
                ('id_roles', models.IntegerField(db_column='ID_Roles', primary_key=True, serialize=False)),
                ('nombre_rol', models.CharField(blank=True, db_column='Nombre_Rol', max_length=50, null=True)),
                ('descripcion_rol', models.CharField(blank=True, db_column='Descripcion_Rol', max_length=100, null=True)),
            ],
            options={
                'db_table': 'Roles',
            },
        ),
        migrations.CreateModel(
            name='Usuarios',
            fields=[
                ('id_usuarios', models.IntegerField(db_column='ID_Usuarios', primary_key=True, serialize=False)),
                ('contrasena', models.CharField(blank=True, db_column='Contrasena', max_length=100, null=True)),
                ('legajo_nro', models.ForeignKey(db_column='Legajo_Nro', on_delete=django.db.models.deletion.DO_NOTHING, to='a_empleados.empleados')),
            ],
            options={
                'db_table': 'Usuarios',
            },
        ),
        migrations.CreateModel(
            name='Empleadosxloccom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('turno', models.CharField(blank=True, db_column='Turno', max_length=20, null=True)),
                ('horas_trabajadas', models.IntegerField(blank=True, db_column='Horas_Trabajadas', null=True)),
                ('id_loc_com', models.ForeignKey(db_column='ID_Loc_Com', on_delete=django.db.models.deletion.DO_NOTHING, to='a_sucursales.localescomerciales')),
                ('legajo_nro', models.ForeignKey(db_column='Legajo_Nro', on_delete=django.db.models.deletion.DO_NOTHING, to='a_empleados.empleados')),
            ],
            options={
                'db_table': 'EmpleadosXLocCom',
                'unique_together': {('legajo_nro', 'id_loc_com')},
            },
        ),
        migrations.CreateModel(
            name='Usuariosxloccom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_inicio', models.DateTimeField(blank=True, db_column='Fecha_Inicio', null=True)),
                ('observaciones', models.CharField(blank=True, db_column='Observaciones', max_length=200, null=True)),
                ('id_loc_com', models.ForeignKey(db_column='ID_Loc_Com', on_delete=django.db.models.deletion.DO_NOTHING, to='a_sucursales.localescomerciales')),
                ('id_usuarios', models.ForeignKey(db_column='ID_Usuarios', on_delete=django.db.models.deletion.DO_NOTHING, to='a_empleados.usuarios')),
            ],
            options={
                'db_table': 'UsuariosXLocCom',
                'unique_together': {('id_usuarios', 'id_loc_com')},
            },
        ),
        migrations.CreateModel(
            name='Usuariosxroles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_asignacion', models.DateTimeField(blank=True, db_column='Fecha_Asignacion', null=True)),
                ('fecha_desvinculacion', models.DateTimeField(blank=True, db_column='Fecha_Desvinculacion', null=True)),
                ('id_roles', models.ForeignKey(db_column='ID_Roles', on_delete=django.db.models.deletion.DO_NOTHING, to='a_empleados.roles')),
                ('id_usuarios', models.ForeignKey(db_column='ID_Usuarios', on_delete=django.db.models.deletion.DO_NOTHING, to='a_empleados.usuarios')),
            ],
            options={
                'db_table': 'UsuariosXRoles',
                'unique_together': {('id_usuarios', 'id_roles')},
            },
        ),
    ]
