# Generated by Django 5.2.5 on 2025-08-24 01:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CodigosPostales',
            fields=[
                ('id_postal', models.IntegerField(db_column='ID_Postal', primary_key=True, serialize=False)),
                ('localidad', models.CharField(blank=True, db_column='Localidad', max_length=100, null=True)),
                ('barrio', models.CharField(blank=True, db_column='Barrio', max_length=50, null=True)),
            ],
            options={
                'db_table': 'Codigos_Postales',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Provincias',
            fields=[
                ('id_provincias', models.IntegerField(db_column='ID_Provincias', primary_key=True, serialize=False)),
                ('nombre_provincia', models.CharField(blank=True, db_column='Nombre_Provincia', max_length=50, null=True)),
                ('zonageog', models.CharField(blank=True, db_column='ZonaGeog', max_length=20, null=True)),
            ],
            options={
                'db_table': 'Provincias',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='LocalesComerciales',
            fields=[
                ('id_loc_com', models.IntegerField(db_column='ID_Loc_Com', primary_key=True, serialize=False)),
                ('nombre_loc_com', models.CharField(blank=True, db_column='Nombre_Loc_Com', max_length=50, null=True)),
                ('telefono_loc_com', models.CharField(blank=True, db_column='Telefono_Loc_Com', max_length=20, null=True)),
                ('email_loc_com', models.CharField(blank=True, db_column='Email_Loc_Com', max_length=50, null=True)),
                ('nombre_calle', models.CharField(blank=True, db_column='Nombre_Calle', max_length=100, null=True)),
                ('nro_calle', models.IntegerField(blank=True, db_column='Nro_Calle', null=True)),
                ('id_postal', models.ForeignKey(db_column='ID_Postal', on_delete=django.db.models.deletion.DO_NOTHING, to='a_sucursales.codigospostales')),
            ],
            options={
                'db_table': 'Locales_Comerciales',
            },
        ),
    ]
