# Generated by Django 5.2.5 on 2025-08-24 01:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('a_caja', '0001_initial'),
        ('a_productos', '0001_initial'),
        ('a_proveedores', '0001_initial'),
        ('a_sucursales', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Compras',
            fields=[
                ('id_compras', models.IntegerField(db_column='ID_Compras', primary_key=True, serialize=False)),
                ('fecha_com', models.DateField(blank=True, db_column='Fecha_Com', null=True)),
                ('hora_com', models.TimeField(blank=True, db_column='Hora_Com', null=True)),
                ('monto_total', models.DecimalField(blank=True, db_column='Monto_Total', decimal_places=2, max_digits=10, null=True)),
                ('ruta_arch_fact', models.CharField(blank=True, db_column='Ruta_Arch_Fact', max_length=500, null=True)),
                ('cuit_pv', models.ForeignKey(db_column='Cuit_Pv', on_delete=django.db.models.deletion.DO_NOTHING, to='a_proveedores.proveedores')),
                ('id_cajas', models.ForeignKey(db_column='ID_Cajas', on_delete=django.db.models.deletion.DO_NOTHING, to='a_caja.cajas')),
                ('id_loc_com', models.ForeignKey(db_column='ID_Loc_Com', on_delete=django.db.models.deletion.DO_NOTHING, to='a_sucursales.localescomerciales')),
            ],
            options={
                'db_table': 'Compras',
            },
        ),
        migrations.CreateModel(
            name='ComprasCanceladas',
            fields=[
                ('id_cc', models.IntegerField(db_column='ID_CC', primary_key=True, serialize=False)),
                ('fecha_cc', models.DateField(blank=True, db_column='Fecha_CC', null=True)),
                ('hora_cc', models.TimeField(blank=True, db_column='Hora_CC', null=True)),
                ('monto_cc', models.DecimalField(blank=True, db_column='Monto_CC', decimal_places=2, max_digits=10, null=True)),
                ('descripcion', models.CharField(blank=True, db_column='Descripcion', max_length=500, null=True)),
                ('id_cajas', models.ForeignKey(db_column='ID_Cajas', on_delete=django.db.models.deletion.DO_NOTHING, to='a_caja.cajas')),
            ],
            options={
                'db_table': 'Compras_Canceladas',
            },
        ),
        migrations.CreateModel(
            name='ReporteInconsistenciaPedidos',
            fields=[
                ('id_rip', models.IntegerField(db_column='ID_RIP', primary_key=True, serialize=False)),
                ('fecha_rip', models.DateField(blank=True, db_column='Fecha_RIP', null=True)),
                ('hora_rip', models.TimeField(blank=True, db_column='Hora_RIP', null=True)),
                ('ruta_ubi_arch_rip', models.CharField(blank=True, db_column='Ruta_Ubi_Arch_RIP', max_length=500, null=True)),
                ('descripcion', models.CharField(blank=True, db_column='Descripcion', max_length=200, null=True)),
                ('id_compras', models.ForeignKey(db_column='ID_Compras', on_delete=django.db.models.deletion.DO_NOTHING, to='a_compras.compras')),
            ],
            options={
                'db_table': 'Reporte_Inconsistencia_Pedidos',
            },
        ),
        migrations.CreateModel(
            name='DetalleCompras',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('precio_unitario', models.DecimalField(blank=True, db_column='Precio_Unitario', decimal_places=2, max_digits=10, null=True)),
                ('cantidad_producto', models.IntegerField(blank=True, db_column='Cantidad_Producto', null=True)),
                ('id_compras', models.ForeignKey(db_column='ID_Compras', on_delete=django.db.models.deletion.DO_NOTHING, to='a_compras.compras')),
                ('id_productos', models.ForeignKey(db_column='ID_Productos', on_delete=django.db.models.deletion.DO_NOTHING, to='a_productos.productos')),
            ],
            options={
                'db_table': 'Detalle_Compras',
                'unique_together': {('id_compras', 'id_productos')},
            },
        ),
    ]
