# Generated by Django 5.2.5 on 2025-09-13 23:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('a_central', '0001_initial'),
        ('a_stock', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Compras',
            fields=[
                ('id_compra', models.BigAutoField(primary_key=True, serialize=False)),
                ('fecha_hora_compra', models.DateTimeField(auto_now_add=True)),
                ('monto_total', models.DecimalField(decimal_places=2, default=0.0, max_digits=14)),
                ('situacion_compra', models.CharField(choices=[('FINALIZADO', 'FINALIZADO'), ('EN_PROCESO', 'EN_PROCESO'), ('CANCELADO', 'CANCELADO')], max_length=10)),
                ('borrado_logico', models.BooleanField(default=False)),
                ('cuit_proveedor', models.ForeignKey(db_column='cuit_proveedor', on_delete=django.db.models.deletion.CASCADE, to='a_stock.proveedores')),
                ('id_sucursal', models.ForeignKey(db_column='id_sucursal', on_delete=django.db.models.deletion.CASCADE, to='a_central.sucursales')),
                ('legajo_empleado', models.ForeignKey(db_column='legajo_empleado', on_delete=django.db.models.deletion.CASCADE, to='a_central.empleados')),
            ],
            options={
                'verbose_name_plural': 'Compras',
                'db_table': 'Compras',
            },
        ),
        migrations.CreateModel(
            name='DetallesCompras',
            fields=[
                ('id_detalle_compra', models.BigAutoField(primary_key=True, serialize=False)),
                ('cantidad', models.BigIntegerField()),
                ('precio_unitario', models.DecimalField(decimal_places=2, max_digits=12)),
                ('borrado_logico', models.BooleanField(default=False)),
                ('id_compra', models.ForeignKey(db_column='id_compra', on_delete=django.db.models.deletion.CASCADE, to='a_compras.compras')),
                ('id_producto', models.ForeignKey(db_column='id_producto', on_delete=django.db.models.deletion.CASCADE, to='a_stock.productos')),
            ],
            options={
                'verbose_name_plural': 'Detalles de Compras',
                'db_table': 'Detalles_Compras',
                'unique_together': {('id_compra', 'id_producto')},
            },
        ),
    ]
