# Generated by Django 5.2.5 on 2025-10-10 20:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('a_central', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Compras',
            fields=[
                ('id_compra', models.AutoField(db_column='ID_Compra', primary_key=True, serialize=False)),
                ('fecha_hora_compra', models.DateTimeField(db_column='Fecha_Hora_Compra')),
                ('monto_total', models.DecimalField(db_column='Monto_Total', decimal_places=2, max_digits=12)),
                ('situacion_compra', models.CharField(choices=[('Pendiente', 'Pendiente'), ('Completada', 'Completada'), ('Cancelada', 'Cancelada')], db_column='Situacion_Compra', default='Completada', max_length=20)),
                ('borrado_compra', models.BooleanField(db_column='Borrado_Compra', default=False)),
                ('fh_borrado_c', models.DateTimeField(blank=True, db_column='FH_Borrado_C', null=True)),
                ('cuit_proveedor', models.ForeignKey(db_column='Cuit_Proveedor', on_delete=django.db.models.deletion.DO_NOTHING, to='a_central.proveedores', to_field='cuit_prov')),
                ('id_sucursal', models.ForeignKey(db_column='ID_Sucursal', on_delete=django.db.models.deletion.DO_NOTHING, to='a_central.localescomerciales', verbose_name='Local Comercial')),
                ('legajo_empleado', models.ForeignKey(db_column='Legajo_Empleado', on_delete=django.db.models.deletion.DO_NOTHING, to='a_central.empleados')),
            ],
            options={
                'verbose_name_plural': 'Compras',
                'db_table': 'Compras',
            },
        ),
        migrations.CreateModel(
            name='IncidenciasCompras',
            fields=[
                ('id_incidencia', models.AutoField(db_column='ID_Incidencia', primary_key=True, serialize=False)),
                ('tipo_problema', models.CharField(db_column='Tipo_Problema', max_length=50)),
                ('cantidad_reportada', models.IntegerField(db_column='Cantidad_Reportada')),
                ('descripcion_incidencia', models.TextField(blank=True, db_column='Descripcion_Incidencia', null=True)),
                ('fh_reporte', models.DateTimeField(db_column='FH_Reporte')),
                ('id_compra', models.ForeignKey(db_column='ID_Compra', on_delete=django.db.models.deletion.DO_NOTHING, to='a_compras.compras')),
                ('id_producto', models.ForeignKey(db_column='ID_Producto', on_delete=django.db.models.deletion.DO_NOTHING, to='a_central.productos')),
            ],
            options={
                'verbose_name_plural': 'Incidencias de Compras',
                'db_table': 'Incidencias_Compras',
            },
        ),
        migrations.CreateModel(
            name='PedidosProveedor',
            fields=[
                ('id_pedido_prov', models.AutoField(db_column='ID_Pedido_Prov', primary_key=True, serialize=False)),
                ('fh_pedido_prov', models.DateTimeField(db_column='FH_Pedido_Prov')),
                ('estado_pedido_prov', models.CharField(db_column='Estado_Pedido_Prov', max_length=50)),
                ('total_estimado', models.DecimalField(blank=True, db_column='Total_Estimado', decimal_places=2, max_digits=10, null=True)),
                ('borrado_ped_prov', models.BooleanField(db_column='Borrado_Ped_Prov', default=False)),
                ('fh_borrado_ped_prov', models.DateTimeField(blank=True, db_column='FH_Borrado_Ped_Prov', null=True)),
                ('id_empleado', models.ForeignKey(blank=True, db_column='ID_Empleado', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='a_central.empleados')),
                ('id_loc_com', models.ForeignKey(db_column='ID_Loc_Com', on_delete=django.db.models.deletion.DO_NOTHING, to='a_central.localescomerciales')),
                ('id_proveedor', models.ForeignKey(db_column='ID_Proveedor', on_delete=django.db.models.deletion.DO_NOTHING, to='a_central.proveedores')),
            ],
            options={
                'verbose_name_plural': 'Pedidos a Proveedores',
                'db_table': 'Pedidos_Proveedor',
            },
        ),
        migrations.CreateModel(
            name='DetallesCompras',
            fields=[
                ('id_detalle_compra', models.AutoField(db_column='ID_Detalle_Compra', primary_key=True, serialize=False)),
                ('cantidad', models.IntegerField(db_column='Cantidad')),
                ('precio_unitario', models.DecimalField(db_column='Precio_Unitario', decimal_places=2, max_digits=10)),
                ('id_compra', models.ForeignKey(db_column='ID_Compra', on_delete=django.db.models.deletion.DO_NOTHING, to='a_compras.compras')),
                ('id_producto', models.ForeignKey(db_column='ID_Producto', on_delete=django.db.models.deletion.DO_NOTHING, to='a_central.productos')),
            ],
            options={
                'verbose_name_plural': 'Detalles de Compras',
                'db_table': 'Detalles_Compras',
                'unique_together': {('id_compra', 'id_producto')},
            },
        ),
        migrations.CreateModel(
            name='DetallePedidosProveedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad_solicitada', models.IntegerField(db_column='Cantidad_Solicitada')),
                ('costo_est_unit', models.DecimalField(blank=True, db_column='Costo_Est_Unit', decimal_places=2, max_digits=10, null=True)),
                ('subtotal_est', models.DecimalField(blank=True, db_column='Subtotal_Est', decimal_places=2, max_digits=10, null=True)),
                ('borrado_det_ped_prov', models.BooleanField(db_column='Borrado_Det_Ped_Prov', default=False)),
                ('fh_borrado_det_ped_prov', models.DateTimeField(blank=True, db_column='FH_Borrado_Det_Ped_Prov', null=True)),
                ('id_producto', models.ForeignKey(db_column='ID_Producto', on_delete=django.db.models.deletion.DO_NOTHING, to='a_central.productos')),
                ('id_pedido_prov', models.ForeignKey(db_column='ID_Pedido_Prov', on_delete=django.db.models.deletion.DO_NOTHING, to='a_compras.pedidosproveedor')),
            ],
            options={
                'verbose_name_plural': 'Detalles de Pedidos a Proveedores',
                'db_table': 'Detalle_Pedidos_Proveedor',
                'unique_together': {('id_pedido_prov', 'id_producto')},
            },
        ),
    ]
