# Generated by Django 5.2.5 on 2025-09-30 13:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('a_central', '0004_billeterasvirtuales_marcas_proveedores_and_more'),
        ('a_compras', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='compras',
            name='borrado_logico',
        ),
        migrations.RemoveField(
            model_name='detallescompras',
            name='borrado_logico',
        ),
        migrations.AddField(
            model_name='compras',
            name='borrado_compra',
            field=models.BooleanField(db_column='Borrado_Compra', default=False),
        ),
        migrations.AddField(
            model_name='compras',
            name='fh_borrado_c',
            field=models.DateTimeField(blank=True, db_column='FH_Borrado_C', null=True),
        ),
        migrations.AlterField(
            model_name='compras',
            name='cuit_proveedor',
            field=models.ForeignKey(db_column='Cuit_Proveedor', on_delete=django.db.models.deletion.DO_NOTHING, to='a_central.proveedores', to_field='cuit_prov'),
        ),
        migrations.AlterField(
            model_name='compras',
            name='fecha_hora_compra',
            field=models.DateTimeField(db_column='Fecha_Hora_Compra'),
        ),
        migrations.AlterField(
            model_name='compras',
            name='id_compra',
            field=models.AutoField(db_column='ID_Compra', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='compras',
            name='id_sucursal',
            field=models.ForeignKey(db_column='ID_Sucursal', on_delete=django.db.models.deletion.DO_NOTHING, to='a_central.localescomerciales', verbose_name='Local Comercial'),
        ),
        migrations.AlterField(
            model_name='compras',
            name='legajo_empleado',
            field=models.ForeignKey(db_column='Legajo_Empleado', on_delete=django.db.models.deletion.DO_NOTHING, to='a_central.empleados'),
        ),
        migrations.AlterField(
            model_name='compras',
            name='monto_total',
            field=models.DecimalField(db_column='Monto_Total', decimal_places=2, max_digits=12),
        ),
        migrations.AlterField(
            model_name='compras',
            name='situacion_compra',
            field=models.CharField(choices=[('Pendiente', 'Pendiente'), ('Completada', 'Completada'), ('Cancelada', 'Cancelada')], db_column='Situacion_Compra', default='Completada', max_length=20),
        ),
        migrations.AlterField(
            model_name='detallescompras',
            name='cantidad',
            field=models.IntegerField(db_column='Cantidad'),
        ),
        migrations.AlterField(
            model_name='detallescompras',
            name='id_compra',
            field=models.ForeignKey(db_column='ID_Compra', on_delete=django.db.models.deletion.DO_NOTHING, to='a_compras.compras'),
        ),
        migrations.AlterField(
            model_name='detallescompras',
            name='id_detalle_compra',
            field=models.AutoField(db_column='ID_Detalle_Compra', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='detallescompras',
            name='id_producto',
            field=models.ForeignKey(db_column='ID_Producto', on_delete=django.db.models.deletion.DO_NOTHING, to='a_central.productos'),
        ),
        migrations.AlterField(
            model_name='detallescompras',
            name='precio_unitario',
            field=models.DecimalField(db_column='Precio_Unitario', decimal_places=2, max_digits=10),
        ),
        migrations.CreateModel(
            name='IncidenciasCompras',
            fields=[
                ('id_incidencia', models.AutoField(db_column='ID_Incidencia', primary_key=True, serialize=False)),
                ('tipo_problema', models.CharField(db_column='Tipo_Problema', max_length=50)),
                ('cantidad_reportada', models.IntegerField(db_column='Cantidad_Reportada')),
                ('descripcion_incidencia', models.TextField(blank=True, db_column='Descripcion_Incidencia', null=True)),
                ('fh_reporte', models.DateTimeField(db_column='FH_Reporte')),
                ('id_compra', models.ForeignKey(db_column='ID_Compra', on_delete=django.db.models.deletion.DO_NOTHING, to='a_compras.compras')),
                ('id_producto', models.ForeignKey(db_column='ID_Producto', on_delete=django.db.models.deletion.DO_NOTHING, to='a_central.productos')),
            ],
            options={
                'verbose_name_plural': 'Incidencias de Compras',
                'db_table': 'Incidencias_Compras',
            },
        ),
        migrations.CreateModel(
            name='PedidosProveedor',
            fields=[
                ('id_pedido_prov', models.AutoField(db_column='ID_Pedido_Prov', primary_key=True, serialize=False)),
                ('fh_pedido_prov', models.DateTimeField(db_column='FH_Pedido_Prov')),
                ('estado_pedido_prov', models.CharField(db_column='Estado_Pedido_Prov', max_length=50)),
                ('total_estimado', models.DecimalField(blank=True, db_column='Total_Estimado', decimal_places=2, max_digits=10, null=True)),
                ('borrado_ped_prov', models.BooleanField(db_column='Borrado_Ped_Prov', default=False)),
                ('fh_borrado_ped_prov', models.DateTimeField(blank=True, db_column='FH_Borrado_Ped_Prov', null=True)),
                ('id_empleado', models.ForeignKey(blank=True, db_column='ID_Empleado', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='a_central.empleados')),
                ('id_loc_com', models.ForeignKey(db_column='ID_Loc_Com', on_delete=django.db.models.deletion.DO_NOTHING, to='a_central.localescomerciales')),
                ('id_proveedor', models.ForeignKey(db_column='ID_Proveedor', on_delete=django.db.models.deletion.DO_NOTHING, to='a_central.proveedores')),
            ],
            options={
                'verbose_name_plural': 'Pedidos a Proveedores',
                'db_table': 'Pedidos_Proveedor',
            },
        ),
        migrations.CreateModel(
            name='DetallePedidosProveedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad_solicitada', models.IntegerField(db_column='Cantidad_Solicitada')),
                ('costo_est_unit', models.DecimalField(blank=True, db_column='Costo_Est_Unit', decimal_places=2, max_digits=10, null=True)),
                ('subtotal_est', models.DecimalField(blank=True, db_column='Subtotal_Est', decimal_places=2, max_digits=10, null=True)),
                ('borrado_det_ped_prov', models.BooleanField(db_column='Borrado_Det_Ped_Prov', default=False)),
                ('fh_borrado_det_ped_prov', models.DateTimeField(blank=True, db_column='FH_Borrado_Det_Ped_Prov', null=True)),
                ('id_producto', models.ForeignKey(db_column='ID_Producto', on_delete=django.db.models.deletion.DO_NOTHING, to='a_central.productos')),
                ('id_pedido_prov', models.ForeignKey(db_column='ID_Pedido_Prov', on_delete=django.db.models.deletion.DO_NOTHING, to='a_compras.pedidosproveedor')),
            ],
            options={
                'verbose_name_plural': 'Detalles de Pedidos a Proveedores',
                'db_table': 'Detalle_Pedidos_Proveedor',
                'unique_together': {('id_pedido_prov', 'id_producto')},
            },
        ),
    ]
