# Generated by Django 5.2.5 on 2025-11-08 13:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('a_central', '0005_alter_billeterasvirtuales_fh_alta_bv_and_more'),
        ('a_compras', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='compras',
            name='id_sucursal',
        ),
        migrations.AddField(
            model_name='compras',
            name='id_loc_com',
            field=models.ForeignKey(db_column='ID_Loc_Com', default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='a_central.localescomerciales', verbose_name='Local Comercial'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='pedidosproveedor',
            name='id_loc_com',
            field=models.ForeignKey(db_column='ID_Loc_Com', on_delete=django.db.models.deletion.DO_NOTHING, to='a_central.localescomerciales', verbose_name='Local Comercial'),
        ),
    ]
