# Generated by Django 5.2.5 on 2025-10-10 20:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('a_central', '0001_initial'),
        ('a_compras', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cajas',
            fields=[
                ('id_caja', models.AutoField(db_column='ID_Caja', primary_key=True, serialize=False)),
                ('numero_caja', models.IntegerField(db_column='Numero_Caja', null=True)),
                ('borrado_caja', models.BooleanField(db_column='Borrado_Caja', default=False)),
                ('fh_borrado_caja', models.DateTimeField(blank=True, db_column='FH_Borrado_Caja', null=True)),
                ('id_loc_com', models.ForeignKey(db_column='ID_Loc_Com', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='a_central.localescomerciales')),
            ],
            options={
                'verbose_name_plural': 'Cajas',
                'db_table': 'Cajas',
            },
        ),
        migrations.CreateModel(
            name='ArqueosCaja',
            fields=[
                ('id_arqueo', models.AutoField(db_column='ID_Arqueo', primary_key=True, serialize=False)),
                ('fh_apertura', models.DateTimeField(db_column='FH_Apertura')),
                ('fh_cierre', models.DateTimeField(blank=True, db_column='FH_Cierre', null=True)),
                ('saldo_apertura', models.DecimalField(db_column='Saldo_Apertura', decimal_places=2, max_digits=12)),
                ('saldo_cierre', models.DecimalField(blank=True, db_column='Saldo_Cierre', decimal_places=2, max_digits=12, null=True)),
                ('monto_sistema', models.DecimalField(blank=True, db_column='Monto_Sistema', decimal_places=2, max_digits=12, null=True)),
                ('diferencia', models.DecimalField(blank=True, db_column='Diferencia', decimal_places=2, max_digits=12, null=True)),
                ('abierto_arqueo', models.BooleanField(blank=True, db_column='Abierto_Arqueo', null=True)),
                ('borrado_arqueo', models.BooleanField(db_column='Borrado_Arqueo', default=False)),
                ('fh_borrado_arqueo', models.DateTimeField(blank=True, db_column='FH_Borrado_Arqueo', null=True)),
                ('id_empleado_apertura', models.ForeignKey(db_column='ID_Empleado_Apertura', on_delete=django.db.models.deletion.DO_NOTHING, related_name='arqueos_aperturados', to='a_central.empleados')),
                ('id_empleado_cierre', models.ForeignKey(blank=True, db_column='ID_Empleado_Cierre', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='arqueos_cerrados', to='a_central.empleados')),
                ('id_caja', models.ForeignKey(db_column='ID_Caja', on_delete=django.db.models.deletion.DO_NOTHING, to='a_cajas.cajas')),
            ],
            options={
                'verbose_name_plural': 'Arqueos de Caja',
                'db_table': 'Arqueos_Caja',
            },
        ),
        migrations.CreateModel(
            name='MovimientosFinancieros',
            fields=[
                ('id_movimiento', models.AutoField(db_column='ID_Movimiento', primary_key=True, serialize=False)),
                ('tipo_movimiento', models.CharField(db_column='Tipo_Movimiento', max_length=20)),
                ('concepto', models.CharField(db_column='Concepto', max_length=200)),
                ('monto', models.DecimalField(db_column='Monto', decimal_places=2, max_digits=12)),
                ('fh_movimiento', models.DateTimeField(db_column='FH_Movimiento')),
                ('borrado_movimiento', models.BooleanField(db_column='Borrado_Movimiento', default=False)),
                ('fh_borrado_movimiento', models.DateTimeField(blank=True, db_column='FH_Borrado_Movimiento', null=True)),
                ('id_bv', models.ForeignKey(blank=True, db_column='ID_BV', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='a_central.billeterasvirtuales')),
                ('id_caja', models.ForeignKey(blank=True, db_column='ID_Caja', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='a_cajas.cajas')),
            ],
            options={
                'verbose_name_plural': 'Movimientos Financieros',
                'db_table': 'Movimientos_Financieros',
            },
        ),
        migrations.CreateModel(
            name='PagosCompras',
            fields=[
                ('id_pago_compra', models.AutoField(db_column='ID_Pago_Compra', primary_key=True, serialize=False)),
                ('monto', models.DecimalField(db_column='Monto', decimal_places=2, max_digits=10)),
                ('fh_pago_compra', models.DateTimeField(db_column='FH_Pago_Compra')),
                ('borrado_pc', models.BooleanField(db_column='Borrado_PC', default=False)),
                ('fh_borrado_pc', models.DateTimeField(blank=True, db_column='FH_Borrado_PC', null=True)),
                ('id_bv', models.ForeignKey(db_column='ID_BV', on_delete=django.db.models.deletion.DO_NOTHING, to='a_central.billeterasvirtuales')),
                ('id_compra', models.ForeignKey(db_column='ID_Compra', on_delete=django.db.models.deletion.DO_NOTHING, to='a_compras.compras')),
            ],
            options={
                'verbose_name_plural': 'Pagos de Compras',
                'db_table': 'Pagos_Compras',
            },
        ),
        migrations.CreateModel(
            name='PagosVentas',
            fields=[
                ('id_pago_venta', models.AutoField(db_column='ID_Pago_Venta', primary_key=True, serialize=False)),
                ('monto', models.DecimalField(db_column='Monto', decimal_places=2, max_digits=10)),
                ('fh_pago_venta', models.DateTimeField(db_column='FH_Pago_Venta')),
                ('borrado_pv', models.BooleanField(db_column='Borrado_PV', default=False)),
                ('fh_borrado_pv', models.DateTimeField(blank=True, db_column='FH_Borrado_PV', null=True)),
                ('id_bv', models.ForeignKey(db_column='ID_BV', on_delete=django.db.models.deletion.DO_NOTHING, to='a_central.billeterasvirtuales')),
            ],
            options={
                'verbose_name_plural': 'Pagos de Ventas',
                'db_table': 'Pagos_Ventas',
            },
        ),
    ]
