# Generated by Django 5.2.5 on 2025-09-13 23:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('a_central', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BilleterasVirtuales',
            fields=[
                ('id_billetera_virtual', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_billetera', models.CharField(max_length=120)),
                ('usuario_billetera', models.CharField(blank=True, max_length=120, null=True)),
                ('contrasena_billetera', models.CharField(blank=True, max_length=255, null=True)),
                ('cvu_billetera', models.CharField(blank=True, max_length=30, null=True, unique=True)),
                ('saldo_billetera', models.DecimalField(decimal_places=2, default=0.0, max_digits=14)),
                ('fecha_alta', models.DateTimeField(auto_now_add=True)),
                ('borrado_logico', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name_plural': 'Billeteras Virtuales',
                'db_table': 'Billeteras_Virtuales',
            },
        ),
        migrations.CreateModel(
            name='Cajas',
            fields=[
                ('id_caja', models.BigAutoField(primary_key=True, serialize=False)),
                ('fecha_apertura', models.DateField()),
                ('hora_apertura', models.TimeField()),
                ('fecha_cierre', models.DateField(blank=True, null=True)),
                ('hora_cierre', models.TimeField(blank=True, null=True)),
                ('importe_inicial', models.DecimalField(decimal_places=2, default=0.0, max_digits=14)),
                ('importe_final', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('abierta', models.BooleanField(default=True)),
                ('borrado_logico', models.BooleanField(default=False)),
                ('id_sucursal', models.ForeignKey(db_column='id_sucursal', on_delete=django.db.models.deletion.CASCADE, to='a_central.sucursales')),
                ('legajo_apertura_caja', models.ForeignKey(db_column='legajo_apertura_caja', on_delete=django.db.models.deletion.CASCADE, related_name='cajas_apertura', to='a_central.empleados')),
                ('legajo_cierre_caja', models.ForeignKey(blank=True, db_column='legajo_cierre_caja', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cajas_cierre', to='a_central.empleados')),
            ],
            options={
                'verbose_name_plural': 'Cajas',
                'db_table': 'Cajas',
            },
        ),
        migrations.CreateModel(
            name='MovimientosCajas',
            fields=[
                ('id_movimiento_caja', models.BigAutoField(primary_key=True, serialize=False)),
                ('tipo_movimiento', models.CharField(choices=[('APERTURA', 'APERTURA'), ('CIERRE', 'CIERRE'), ('VENTA_EFECTIVO', 'VENTA_EFECTIVO'), ('VENTA_BILLETERA', 'VENTA_BILLETERA'), ('COMPRA_EFECTIVO', 'COMPRA_EFECTIVO'), ('COMPRA_BILLETERA', 'COMPRA_BILLETERA'), ('RETIRO', 'RETIRO'), ('AJUSTE', 'AJUSTE')], max_length=16)),
                ('monto', models.DecimalField(decimal_places=2, max_digits=14)),
                ('descripcion', models.CharField(blank=True, max_length=255, null=True)),
                ('fecha_hora', models.DateTimeField(auto_now_add=True)),
                ('borrado_logico', models.BooleanField(default=False)),
                ('id_caja', models.ForeignKey(db_column='id_caja', on_delete=django.db.models.deletion.CASCADE, to='a_cajas.cajas')),
            ],
            options={
                'verbose_name_plural': 'Movimientos de Cajas',
                'db_table': 'Movimientos_Cajas',
            },
        ),
    ]
