# Generated by Django 5.2.5 on 2025-09-30 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('a_cajas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArqueosCaja',
            fields=[
                ('id_arqueo', models.AutoField(db_column='ID_Arqueo', primary_key=True, serialize=False)),
                ('fh_apertura', models.DateTimeField(db_column='FH_Apertura')),
                ('fh_cierre', models.DateTimeField(blank=True, db_column='FH_Cierre', null=True)),
                ('saldo_apertura', models.DecimalField(db_column='Saldo_Apertura', decimal_places=2, max_digits=12)),
                ('saldo_cierre', models.DecimalField(blank=True, db_column='Saldo_Cierre', decimal_places=2, max_digits=12, null=True)),
                ('monto_sistema', models.DecimalField(blank=True, db_column='Monto_Sistema', decimal_places=2, max_digits=12, null=True)),
                ('diferencia', models.DecimalField(blank=True, db_column='Diferencia', decimal_places=2, max_digits=12, null=True)),
                ('abierto_arqueo', models.BooleanField(blank=True, db_column='Abierto_Arqueo', null=True)),
                ('borrado_arqueo', models.BooleanField(db_column='Borrado_Arqueo', default=False)),
                ('fh_borrado_arqueo', models.DateTimeField(blank=True, db_column='FH_Borrado_Arqueo', null=True)),
            ],
            options={
                'verbose_name_plural': 'Arqueos de Caja',
                'db_table': 'Arqueos_Caja',
            },
        ),
        migrations.CreateModel(
            name='MovimientosFinancieros',
            fields=[
                ('id_movimiento', models.AutoField(db_column='ID_Movimiento', primary_key=True, serialize=False)),
                ('tipo_movimiento', models.CharField(db_column='Tipo_Movimiento', max_length=20)),
                ('concepto', models.CharField(db_column='Concepto', max_length=200)),
                ('monto', models.DecimalField(db_column='Monto', decimal_places=2, max_digits=12)),
                ('fh_movimiento', models.DateTimeField(db_column='FH_Movimiento')),
                ('borrado_movimiento', models.BooleanField(db_column='Borrado_Movimiento', default=False)),
                ('fh_borrado_movimiento', models.DateTimeField(blank=True, db_column='FH_Borrado_Movimiento', null=True)),
            ],
            options={
                'verbose_name_plural': 'Movimientos Financieros',
                'db_table': 'Movimientos_Financieros',
            },
        ),
        migrations.CreateModel(
            name='PagosCompras',
            fields=[
                ('id_pago_compra', models.AutoField(db_column='ID_Pago_Compra', primary_key=True, serialize=False)),
                ('monto', models.DecimalField(db_column='Monto', decimal_places=2, max_digits=10)),
                ('fh_pago_compra', models.DateTimeField(db_column='FH_Pago_Compra')),
                ('borrado_pc', models.BooleanField(db_column='Borrado_PC', default=False)),
                ('fh_borrado_pc', models.DateTimeField(blank=True, db_column='FH_Borrado_PC', null=True)),
            ],
            options={
                'verbose_name_plural': 'Pagos de Compras',
                'db_table': 'Pagos_Compras',
            },
        ),
        migrations.CreateModel(
            name='PagosVentas',
            fields=[
                ('id_pago_venta', models.AutoField(db_column='ID_Pago_Venta', primary_key=True, serialize=False)),
                ('monto', models.DecimalField(db_column='Monto', decimal_places=2, max_digits=10)),
                ('fh_pago_venta', models.DateTimeField(db_column='FH_Pago_Venta')),
                ('borrado_pv', models.BooleanField(db_column='Borrado_PV', default=False)),
                ('fh_borrado_pv', models.DateTimeField(blank=True, db_column='FH_Borrado_PV', null=True)),
            ],
            options={
                'verbose_name_plural': 'Pagos de Ventas',
                'db_table': 'Pagos_Ventas',
            },
        ),
        migrations.DeleteModel(
            name='BilleterasVirtuales',
        ),
        migrations.RemoveField(
            model_name='movimientoscajas',
            name='id_caja',
        ),
    ]
