# Generated by Django 5.2.5 on 2025-10-10 20:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('a_cajas', '0001_initial'),
        ('a_ventas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pagosventas',
            name='id_venta',
            field=models.ForeignKey(db_column='ID_Venta', on_delete=django.db.models.deletion.DO_NOTHING, to='a_ventas.ventas'),
        ),
        migrations.AlterUniqueTogether(
            name='cajas',
            unique_together={('id_loc_com', 'numero_caja')},
        ),
    ]
