# Generated by Django 5.2.5 on 2025-10-12 16:18

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('a_cajas', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cajas',
            name='fh_alta_caja',
            field=models.DateTimeField(db_column='FH_Alta_Caja', default=django.utils.timezone.now),
        ),
    ]
