# Generated by Django 5.2.5 on 2025-09-30 13:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('a_cajas', '0002_arqueoscaja_movimientosfinancieros_pagoscompras_and_more'),
        ('a_central', '0004_billeterasvirtuales_marcas_proveedores_and_more'),
        ('a_compras', '0002_remove_compras_borrado_logico_and_more'),
        ('a_ventas', '0002_remove_detallesventas_borrado_logico_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='cajas',
            unique_together={('id_loc_com', 'numero_caja')},
        ),
        migrations.AddField(
            model_name='cajas',
            name='borrado_caja',
            field=models.BooleanField(db_column='Borrado_Caja', default=False),
        ),
        migrations.AddField(
            model_name='cajas',
            name='fh_borrado_caja',
            field=models.DateTimeField(blank=True, db_column='FH_Borrado_Caja', null=True),
        ),
        migrations.AddField(
            model_name='cajas',
            name='id_loc_com',
            field=models.ForeignKey(db_column='ID_Loc_Com', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='a_central.localescomerciales'),
        ),
        migrations.AddField(
            model_name='cajas',
            name='numero_caja',
            field=models.IntegerField(db_column='Numero_Caja', null=True),
        ),
        migrations.AlterField(
            model_name='cajas',
            name='id_caja',
            field=models.AutoField(db_column='ID_Caja', primary_key=True, serialize=False),
        ),
        migrations.AddField(
            model_name='arqueoscaja',
            name='id_caja',
            field=models.ForeignKey(db_column='ID_Caja', on_delete=django.db.models.deletion.DO_NOTHING, to='a_cajas.cajas'),
        ),
        migrations.AddField(
            model_name='arqueoscaja',
            name='id_empleado_apertura',
            field=models.ForeignKey(db_column='ID_Empleado_Apertura', on_delete=django.db.models.deletion.DO_NOTHING, related_name='arqueos_aperturados', to='a_central.empleados'),
        ),
        migrations.AddField(
            model_name='arqueoscaja',
            name='id_empleado_cierre',
            field=models.ForeignKey(blank=True, db_column='ID_Empleado_Cierre', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='arqueos_cerrados', to='a_central.empleados'),
        ),
        migrations.AddField(
            model_name='movimientosfinancieros',
            name='id_bv',
            field=models.ForeignKey(blank=True, db_column='ID_BV', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='a_central.billeterasvirtuales'),
        ),
        migrations.AddField(
            model_name='movimientosfinancieros',
            name='id_caja',
            field=models.ForeignKey(blank=True, db_column='ID_Caja', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='a_cajas.cajas'),
        ),
        migrations.AddField(
            model_name='pagoscompras',
            name='id_bv',
            field=models.ForeignKey(db_column='ID_BV', on_delete=django.db.models.deletion.DO_NOTHING, to='a_central.billeterasvirtuales'),
        ),
        migrations.AddField(
            model_name='pagoscompras',
            name='id_compra',
            field=models.ForeignKey(db_column='ID_Compra', on_delete=django.db.models.deletion.DO_NOTHING, to='a_compras.compras'),
        ),
        migrations.AddField(
            model_name='pagosventas',
            name='id_bv',
            field=models.ForeignKey(db_column='ID_BV', on_delete=django.db.models.deletion.DO_NOTHING, to='a_central.billeterasvirtuales'),
        ),
        migrations.AddField(
            model_name='pagosventas',
            name='id_venta',
            field=models.ForeignKey(db_column='ID_Venta', on_delete=django.db.models.deletion.DO_NOTHING, to='a_ventas.ventas'),
        ),
        migrations.DeleteModel(
            name='MovimientosCajas',
        ),
        migrations.RemoveField(
            model_name='cajas',
            name='abierta',
        ),
        migrations.RemoveField(
            model_name='cajas',
            name='borrado_logico',
        ),
        migrations.RemoveField(
            model_name='cajas',
            name='fecha_apertura',
        ),
        migrations.RemoveField(
            model_name='cajas',
            name='fecha_cierre',
        ),
        migrations.RemoveField(
            model_name='cajas',
            name='hora_apertura',
        ),
        migrations.RemoveField(
            model_name='cajas',
            name='hora_cierre',
        ),
        migrations.RemoveField(
            model_name='cajas',
            name='id_sucursal',
        ),
        migrations.RemoveField(
            model_name='cajas',
            name='importe_final',
        ),
        migrations.RemoveField(
            model_name='cajas',
            name='importe_inicial',
        ),
        migrations.RemoveField(
            model_name='cajas',
            name='legajo_apertura_caja',
        ),
        migrations.RemoveField(
            model_name='cajas',
            name='legajo_cierre_caja',
        ),
    ]
