# Generated by Django 5.2.5 on 2025-10-13 15:29

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('a_cajas', '0003_cajas_fh_alta_caja'),
    ]

    operations = [
        migrations.AddField(
            model_name='cajas',
            name='caja_abierta',
            field=models.BooleanField(db_column='Caja_Abierta', default=False, help_text='Indica si la caja está actualmente abierta para transacciones.'),
        ),
        migrations.AlterField(
            model_name='arqueoscaja',
            name='abierto_arqueo',
            field=models.BooleanField(db_column='Abierto_Arqueo', default=True),
        ),
        migrations.AlterField(
            model_name='arqueoscaja',
            name='fh_apertura',
            field=models.DateTimeField(db_column='FH_Apertura', default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='movimientosfinancieros',
            name='fh_movimiento',
            field=models.DateTimeField(db_column='FH_Movimiento', default=django.utils.timezone.now),
        ),
    ]
