# Generated by Django 5.2.5 on 2025-10-13 19:29

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('a_cajas', '0004_cajas_caja_abierta_alter_arqueoscaja_abierto_arqueo_and_more'),
        ('a_central', '0005_alter_billeterasvirtuales_fh_alta_bv_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movimientosfinancieros',
            name='id_caja',
        ),
        migrations.AddField(
            model_name='movimientosfinancieros',
            name='medio_pago',
            field=models.CharField(db_column='Medio_Pago', default='EFECTIVO', max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='pagoscompras',
            name='fh_pago_compra',
            field=models.DateTimeField(db_column='FH_Pago_Compra', default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='pagosventas',
            name='fh_pago_venta',
            field=models.DateTimeField(db_column='FH_Pago_Venta', default=django.utils.timezone.now),
        ),
        migrations.CreateModel(
            name='ArqueoCaja',
            fields=[
                ('id_arqueo', models.AutoField(db_column='ID_Arqueo', primary_key=True, serialize=False)),
                ('fh_apertura', models.DateTimeField(db_column='FH_Apertura', default=django.utils.timezone.now)),
                ('monto_inicial_efectivo', models.DecimalField(db_column='Monto_Inicial_Efectivo', decimal_places=2, max_digits=12)),
                ('fh_cierre', models.DateTimeField(blank=True, db_column='FH_Cierre', null=True)),
                ('monto_final_efectivo', models.DecimalField(blank=True, db_column='Monto_Final_Efectivo', decimal_places=2, max_digits=12, null=True)),
                ('total_ingresos_efectivo_calculado', models.DecimalField(db_column='Total_Ingresos_Efectivo_Calculado', decimal_places=2, default=0, max_digits=12)),
                ('total_egresos_efectivo_calculado', models.DecimalField(db_column='Total_Egresos_Efectivo_Calculado', decimal_places=2, default=0, max_digits=12)),
                ('total_ingresos_bv', models.DecimalField(db_column='Total_Ingresos_BV', decimal_places=2, default=0, max_digits=12)),
                ('total_egresos_bv', models.DecimalField(db_column='Total_Egresos_BV', decimal_places=2, default=0, max_digits=12)),
                ('diferencia_arqueo', models.DecimalField(blank=True, db_column='Diferencia_Arqueo', decimal_places=2, max_digits=12, null=True)),
                ('observaciones', models.TextField(blank=True, db_column='Observaciones', null=True)),
                ('cerrado', models.BooleanField(db_column='Cerrado', default=False)),
                ('id_caja', models.ForeignKey(db_column='ID_Caja', on_delete=django.db.models.deletion.DO_NOTHING, to='a_cajas.cajas')),
                ('id_empleado_apertura', models.ForeignKey(db_column='ID_Empleado_Apertura', on_delete=django.db.models.deletion.DO_NOTHING, related_name='arqueos_abiertos', to='a_central.empleados')),
                ('id_empleado_cierre', models.ForeignKey(blank=True, db_column='ID_Empleado_Cierre', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='arqueos_cerrados', to='a_central.empleados')),
            ],
            options={
                'verbose_name_plural': 'Arqueos de Caja',
                'db_table': 'Arqueo_Caja',
            },
        ),
        migrations.AddField(
            model_name='movimientosfinancieros',
            name='id_arqueo',
            field=models.ForeignKey(blank=True, db_column='ID_Arqueo', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='a_cajas.arqueocaja'),
        ),
        migrations.DeleteModel(
            name='ArqueosCaja',
        ),
    ]
