# Generated by Django 5.2.5 on 2025-11-23 03:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('a_cajas', '0005_remove_movimientosfinancieros_id_caja_and_more'),
        ('a_compras', '0002_remove_compras_id_sucursal_compras_id_loc_com_and_more'),
        ('a_ventas', '0002_alter_detallesventas_id_venta_alter_ventas_fh_venta_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='movimientosfinancieros',
            name='id_compra',
            field=models.ForeignKey(blank=True, db_column='ID_Compra', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='a_compras.compras'),
        ),
        migrations.AddField(
            model_name='movimientosfinancieros',
            name='id_venta',
            field=models.ForeignKey(blank=True, db_column='ID_Venta', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='a_ventas.ventas'),
        ),
    ]
