# Generated by Django 5.2.5 on 2025-10-10 20:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BilleterasVirtuales',
            fields=[
                ('id_bv', models.AutoField(db_column='ID_BV', primary_key=True, serialize=False)),
                ('nombre_bv', models.CharField(db_column='Nombre_BV', max_length=100)),
                ('usuario_bv', models.CharField(db_column='Usuario_BV', max_length=100, unique=True)),
                ('contrasena_bv', models.CharField(db_column='Contrasena_BV', max_length=255)),
                ('cbu_bv', models.CharField(blank=True, db_column='CBU_BV', max_length=22, null=True, unique=True)),
                ('fh_alta_bv', models.DateTimeField(db_column='FH_Alta_BV')),
                ('fh_baja_bv', models.DateTimeField(blank=True, db_column='FH_Baja_BV', null=True)),
                ('saldo_bv', models.DecimalField(blank=True, db_column='Saldo_BV', decimal_places=2, max_digits=12, null=True)),
                ('borrado_bv', models.BooleanField(db_column='Borrado_BV', default=False)),
                ('fh_borrado_bv', models.DateTimeField(blank=True, db_column='FH_Borrado_BV', null=True)),
            ],
            options={
                'verbose_name_plural': 'Billeteras Virtuales',
                'db_table': 'Billeteras_Virtuales',
            },
        ),
        migrations.CreateModel(
            name='Marcas',
            fields=[
                ('id_marca', models.AutoField(db_column='ID_Marca', primary_key=True, serialize=False)),
                ('nombre_marca', models.CharField(db_column='Nombre_Marca', max_length=50, unique=True)),
                ('borrado_marca', models.BooleanField(db_column='Borrado_Marca', default=False)),
                ('fh_borrado_m', models.DateTimeField(blank=True, db_column='FH_Borrado_M', null=True)),
            ],
            options={
                'db_table': 'Marcas',
            },
        ),
        migrations.CreateModel(
            name='Proveedores',
            fields=[
                ('id_proveedor', models.AutoField(db_column='ID_Proveedor', primary_key=True, serialize=False)),
                ('cuit_prov', models.CharField(db_column='Cuit_Prov', max_length=15, unique=True)),
                ('nombre_prov', models.CharField(db_column='Nombre_Prov', max_length=150)),
                ('telefono_prov', models.CharField(blank=True, db_column='Telefono_Prov', max_length=20, null=True)),
                ('email_prov', models.CharField(blank=True, db_column='Email_Prov', max_length=150, null=True)),
                ('direccion_prov', models.CharField(blank=True, db_column='Direccion_Prov', max_length=100, null=True)),
                ('borrado_prov', models.BooleanField(db_column='Borrado_Prov', default=False)),
                ('fh_borrado_prov', models.DateTimeField(blank=True, db_column='FH_Borrado_Prov', null=True)),
            ],
            options={
                'verbose_name_plural': 'Proveedores',
                'db_table': 'Proveedores',
            },
        ),
        migrations.CreateModel(
            name='Provincias',
            fields=[
                ('id_provincia', models.AutoField(db_column='ID_Provincia', primary_key=True, serialize=False)),
                ('nombre_provincia', models.CharField(db_column='Nombre_Provincia', max_length=50, unique=True)),
                ('borrado_provincia', models.BooleanField(db_column='Borrado_Provincia', default=False)),
                ('fh_borrado_p', models.DateTimeField(blank=True, db_column='FH_Borrado_P', null=True)),
            ],
            options={
                'verbose_name_plural': 'Provincias',
                'db_table': 'Provincias',
            },
        ),
        migrations.CreateModel(
            name='Empleados',
            fields=[
                ('id_empleado', models.AutoField(db_column='ID_Empleado', primary_key=True, serialize=False)),
                ('dni_emp', models.BigIntegerField(db_column='DNI_Emp', unique=True)),
                ('apellido_emp', models.CharField(db_column='Apellido_Emp', max_length=80)),
                ('nombre_emp', models.CharField(db_column='Nombre_Emp', max_length=80)),
                ('email_emp', models.CharField(db_column='Email_Emp', max_length=150, unique=True)),
                ('usuario_emp', models.CharField(blank=True, db_column='Usuario_Emp', max_length=50, null=True, unique=True)),
                ('contrasena_emp', models.CharField(db_column='Contrasena_Emp', max_length=255)),
                ('telefono_emp', models.CharField(blank=True, db_column='Telefono_Emp', max_length=20, null=True)),
                ('domicilio_emp', models.CharField(blank=True, db_column='Domicilio_Emp', max_length=200, null=True)),
                ('fecha_alta_emp', models.DateField(db_column='Fecha_Alta_Emp')),
                ('fecha_baja_emp', models.DateField(blank=True, db_column='Fecha_Baja_Emp', null=True)),
                ('borrado_emp', models.BooleanField(db_column='Borrado_Emp', default=False)),
                ('fh_borrado_e', models.DateTimeField(blank=True, db_column='FH_Borrado_E', null=True)),
                ('user_auth', models.OneToOneField(blank=True, db_column='ID_User_Auth', null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Usuario del Sistema de Auth')),
            ],
            options={
                'verbose_name_plural': 'Empleados',
                'db_table': 'Empleados',
            },
        ),
        migrations.CreateModel(
            name='Auditorias',
            fields=[
                ('id_auditoria', models.AutoField(db_column='ID_Auditoria', primary_key=True, serialize=False)),
                ('nombre_tabla', models.CharField(db_column='Nombre_Tabla', max_length=50)),
                ('id_registro', models.IntegerField(db_column='ID_Registro')),
                ('accion_auditoria', models.CharField(db_column='Accion_Auditoria', max_length=10)),
                ('datos_anteriores', models.JSONField(blank=True, db_column='Datos_Anteriores', null=True)),
                ('datos_nuevos', models.JSONField(blank=True, db_column='Datos_Nuevos', null=True)),
                ('fh_accion', models.DateTimeField(db_column='FH_Accion')),
                ('id_usuario', models.ForeignKey(blank=True, db_column='ID_Usuario', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='a_central.empleados')),
            ],
            options={
                'verbose_name_plural': 'Auditorias',
                'db_table': 'Auditorias',
            },
        ),
        migrations.CreateModel(
            name='Productos',
            fields=[
                ('id_producto', models.AutoField(db_column='ID_Producto', primary_key=True, serialize=False)),
                ('nombre_producto', models.CharField(blank=True, db_column='Nombre_Producto', max_length=150, null=True)),
                ('precio_unit_prod', models.DecimalField(blank=True, db_column='Precio_Unit_Prod', decimal_places=2, max_digits=10, null=True)),
                ('fecha_venc_prod', models.DateField(blank=True, db_column='Fecha_Venc_Prod', null=True)),
                ('borrado_prod', models.BooleanField(db_column='Borrado_Prod', default=False)),
                ('fh_borrado_prod', models.DateTimeField(blank=True, db_column='FH_Borrado_Prod', null=True)),
                ('id_marca', models.ForeignKey(blank=True, db_column='ID_Marca', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='a_central.marcas')),
            ],
            options={
                'verbose_name_plural': 'Productos',
                'db_table': 'Productos',
            },
        ),
        migrations.CreateModel(
            name='LocalesComerciales',
            fields=[
                ('id_loc_com', models.AutoField(db_column='ID_Loc_Com', primary_key=True, serialize=False)),
                ('nombre_loc_com', models.CharField(db_column='Nombre_Loc_Com', max_length=100)),
                ('cod_postal_loc_com', models.IntegerField(blank=True, db_column='Cod_Postal_Loc_Com', null=True)),
                ('telefono_loc_com', models.CharField(blank=True, db_column='Telefono_Loc_Com', max_length=30, null=True)),
                ('direccion_loc_com', models.CharField(blank=True, db_column='Direccion_Loc_Com', max_length=100, null=True)),
                ('borrado_loc_com', models.BooleanField(db_column='Borrado_Loc_Com', default=False)),
                ('fh_borrado_lc', models.DateTimeField(blank=True, db_column='FH_Borrado_LC', null=True)),
                ('id_provincia', models.ForeignKey(db_column='ID_Provincia', on_delete=django.db.models.deletion.DO_NOTHING, to='a_central.provincias')),
            ],
            options={
                'verbose_name_plural': 'Locales Comerciales',
                'db_table': 'Locales_Comerciales',
                'unique_together': {('id_provincia', 'nombre_loc_com')},
            },
        ),
        migrations.CreateModel(
            name='Empleadosxloccom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('turno_exlc', models.CharField(db_column='Turno_ExLC', max_length=20)),
                ('horas_trabajadas', models.IntegerField(db_column='Horas_Trabajadas')),
                ('id_empleado', models.ForeignKey(db_column='ID_Empleado', on_delete=django.db.models.deletion.DO_NOTHING, to='a_central.empleados')),
                ('id_loc_com', models.ForeignKey(db_column='ID_Loc_Com', on_delete=django.db.models.deletion.DO_NOTHING, to='a_central.localescomerciales')),
            ],
            options={
                'verbose_name_plural': 'Empleados por Local Comercial',
                'db_table': 'EmpleadosXLocCom',
                'unique_together': {('id_empleado', 'id_loc_com')},
            },
        ),
    ]
