# Generated by Django 5.2.5 on 2025-09-13 22:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Empleados',
            fields=[
                ('legajo_nro_empleado', models.AutoField(primary_key=True, serialize=False)),
                ('dni_empleado', models.CharField(max_length=20, unique=True)),
                ('apellido_empleado', models.CharField(max_length=80)),
                ('nombre_empleado', models.CharField(max_length=80)),
                ('email_empleado', models.CharField(blank=True, max_length=150, null=True)),
                ('telefono_empleado', models.CharField(blank=True, max_length=30, null=True)),
                ('domicilio_empleado', models.CharField(blank=True, max_length=200, null=True)),
                ('fecha_alta', models.DateField(auto_now_add=True)),
                ('fecha_baja', models.DateField(blank=True, null=True)),
                ('contrasena_empleado', models.CharField(max_length=255)),
                ('borrado_logico', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name_plural': 'Empleados',
                'db_table': 'Empleados',
            },
        ),
        migrations.CreateModel(
            name='Provincias',
            fields=[
                ('id_provincia', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_provincia', models.CharField(max_length=50, unique=True)),
                ('borrado_logico', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name_plural': 'Provincias',
                'db_table': 'Provincias',
            },
        ),
        migrations.CreateModel(
            name='Roles',
            fields=[
                ('id_rol', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_rol', models.CharField(max_length=50, unique=True)),
                ('descripcion_rol', models.CharField(blank=True, max_length=100, null=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_modificacion', models.DateTimeField(auto_now=True)),
                ('borrado_logico', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name_plural': 'Roles',
                'db_table': 'Roles',
            },
        ),
        migrations.CreateModel(
            name='Auditorias',
            fields=[
                ('id_auditoria', models.BigAutoField(primary_key=True, serialize=False)),
                ('tabla_afectada', models.CharField(max_length=100)),
                ('accion', models.CharField(choices=[('INSERT', 'INSERT'), ('UPDATE', 'UPDATE'), ('DELETE', 'DELETE')], max_length=6)),
                ('registro_pk', models.CharField(max_length=120)),
                ('datos_previos', models.JSONField(blank=True, null=True)),
                ('datos_nuevos', models.JSONField(blank=True, null=True)),
                ('fecha_hora', models.DateTimeField(auto_now_add=True)),
                ('ip_cliente', models.CharField(blank=True, max_length=64, null=True)),
                ('borrado_logico', models.BooleanField(default=False)),
                ('legajo_empleado', models.ForeignKey(blank=True, db_column='legajo_empleado', null=True, on_delete=django.db.models.deletion.SET_NULL, to='a_central.empleados')),
            ],
            options={
                'verbose_name_plural': 'Auditorias',
                'db_table': 'Auditorias',
            },
        ),
        migrations.AddField(
            model_name='empleados',
            name='id_rol',
            field=models.ForeignKey(db_column='id_rol', on_delete=django.db.models.deletion.CASCADE, to='a_central.roles'),
        ),
        migrations.CreateModel(
            name='Sucursales',
            fields=[
                ('id_sucursal', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_sucursal', models.CharField(max_length=120)),
                ('cod_postal_suc', models.CharField(blank=True, max_length=10, null=True)),
                ('telefono_suc', models.CharField(blank=True, max_length=30, null=True)),
                ('direccion_suc', models.CharField(blank=True, max_length=200, null=True)),
                ('borrado_logico', models.BooleanField(default=False)),
                ('id_provincia', models.ForeignKey(db_column='id_provincia', on_delete=django.db.models.deletion.CASCADE, to='a_central.provincias')),
            ],
            options={
                'verbose_name_plural': 'Sucursales',
                'db_table': 'Sucursales',
            },
        ),
        migrations.AddField(
            model_name='empleados',
            name='id_sucursal',
            field=models.ForeignKey(db_column='id_sucursal', on_delete=django.db.models.deletion.CASCADE, to='a_central.sucursales'),
        ),
    ]
