# Generated by Django 5.2.5 on 2025-09-14 01:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('a_central', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='roles',
            name='fecha_borrado',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
