# Generated by Django 5.2.5 on 2025-10-12 12:29

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('a_central', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='marcas',
            options={'verbose_name_plural': 'Marcas'},
        ),
        migrations.AddField(
            model_name='proveedores',
            name='fecha_alta_prov',
            field=models.DateTimeField(auto_now_add=True, db_column='Fecha_Alta_Prov', default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
