# Generated by Django 5.2.5 on 2025-09-16 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('a_central', '0002_roles_fecha_borrado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empleados',
            name='dni_empleado',
            field=models.BigIntegerField(unique=True),
        ),
    ]
