# Generated by Django 5.2.5 on 2025-10-12 14:35

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('a_central', '0002_alter_marcas_options_proveedores_fecha_alta_prov'),
    ]

    operations = [
        migrations.AddField(
            model_name='localescomerciales',
            name='fecha_alta_loc_com',
            field=models.DateTimeField(auto_now_add=True, db_column='Fecha_Alta_Loc_Com', default=datetime.datetime(2025, 10, 12, 14, 35, 39, 160630, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
    ]
