# Generated by Django 5.2.5 on 2025-09-30 13:59

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('a_central', '0003_alter_empleados_dni_empleado'),
    ]

    operations = [
        migrations.CreateModel(
            name='BilleterasVirtuales',
            fields=[
                ('id_bv', models.AutoField(db_column='ID_BV', primary_key=True, serialize=False)),
                ('nombre_bv', models.CharField(db_column='Nombre_BV', max_length=100)),
                ('usuario_bv', models.CharField(db_column='Usuario_BV', max_length=100, unique=True)),
                ('contrasena_bv', models.CharField(db_column='Contrasena_BV', max_length=255)),
                ('cbu_bv', models.CharField(blank=True, db_column='CBU_BV', max_length=22, null=True, unique=True)),
                ('fh_alta_bv', models.DateTimeField(db_column='FH_Alta_BV')),
                ('fh_baja_bv', models.DateTimeField(blank=True, db_column='FH_Baja_BV', null=True)),
                ('saldo_bv', models.DecimalField(blank=True, db_column='Saldo_BV', decimal_places=2, max_digits=12, null=True)),
                ('borrado_bv', models.BooleanField(db_column='Borrado_BV', default=False)),
                ('fh_borrado_bv', models.DateTimeField(blank=True, db_column='FH_Borrado_BV', null=True)),
            ],
            options={
                'verbose_name_plural': 'Billeteras Virtuales',
                'db_table': 'Billeteras_Virtuales',
            },
        ),
        migrations.CreateModel(
            name='Marcas',
            fields=[
                ('id_marca', models.AutoField(db_column='ID_Marca', primary_key=True, serialize=False)),
                ('nombre_marca', models.CharField(db_column='Nombre_Marca', max_length=50, unique=True)),
                ('borrado_marca', models.BooleanField(db_column='Borrado_Marca', default=False)),
                ('fh_borrado_m', models.DateTimeField(blank=True, db_column='FH_Borrado_M', null=True)),
            ],
            options={
                'db_table': 'Marcas',
            },
        ),
        migrations.CreateModel(
            name='Proveedores',
            fields=[
                ('id_proveedor', models.AutoField(db_column='ID_Proveedor', primary_key=True, serialize=False)),
                ('cuit_prov', models.CharField(db_column='Cuit_Prov', max_length=15, unique=True)),
                ('nombre_prov', models.CharField(db_column='Nombre_Prov', max_length=150)),
                ('telefono_prov', models.CharField(blank=True, db_column='Telefono_Prov', max_length=20, null=True)),
                ('email_prov', models.CharField(blank=True, db_column='Email_Prov', max_length=150, null=True)),
                ('direccion_prov', models.CharField(blank=True, db_column='Direccion_Prov', max_length=100, null=True)),
                ('borrado_prov', models.BooleanField(db_column='Borrado_Prov', default=False)),
                ('fh_borrado_prov', models.DateTimeField(blank=True, db_column='FH_Borrado_Prov', null=True)),
            ],
            options={
                'verbose_name_plural': 'Proveedores',
                'db_table': 'Proveedores',
            },
        ),
        migrations.RemoveField(
            model_name='empleados',
            name='id_rol',
        ),
        migrations.RemoveField(
            model_name='sucursales',
            name='id_provincia',
        ),
        migrations.RemoveField(
            model_name='empleados',
            name='id_sucursal',
        ),
        migrations.RemoveField(
            model_name='auditorias',
            name='accion',
        ),
        migrations.RemoveField(
            model_name='auditorias',
            name='borrado_logico',
        ),
        migrations.RemoveField(
            model_name='auditorias',
            name='datos_previos',
        ),
        migrations.RemoveField(
            model_name='auditorias',
            name='fecha_hora',
        ),
        migrations.RemoveField(
            model_name='auditorias',
            name='ip_cliente',
        ),
        migrations.RemoveField(
            model_name='auditorias',
            name='legajo_empleado',
        ),
        migrations.RemoveField(
            model_name='auditorias',
            name='registro_pk',
        ),
        migrations.RemoveField(
            model_name='auditorias',
            name='tabla_afectada',
        ),
        migrations.RemoveField(
            model_name='empleados',
            name='apellido_empleado',
        ),
        migrations.RemoveField(
            model_name='empleados',
            name='borrado_logico',
        ),
        migrations.RemoveField(
            model_name='empleados',
            name='contrasena_empleado',
        ),
        migrations.RemoveField(
            model_name='empleados',
            name='dni_empleado',
        ),
        migrations.RemoveField(
            model_name='empleados',
            name='domicilio_empleado',
        ),
        migrations.RemoveField(
            model_name='empleados',
            name='email_empleado',
        ),
        migrations.RemoveField(
            model_name='empleados',
            name='fecha_alta',
        ),
        migrations.RemoveField(
            model_name='empleados',
            name='fecha_baja',
        ),
        migrations.RemoveField(
            model_name='empleados',
            name='legajo_nro_empleado',
        ),
        migrations.RemoveField(
            model_name='empleados',
            name='nombre_empleado',
        ),
        migrations.RemoveField(
            model_name='empleados',
            name='telefono_empleado',
        ),
        migrations.RemoveField(
            model_name='provincias',
            name='borrado_logico',
        ),
        migrations.AddField(
            model_name='auditorias',
            name='accion_auditoria',
            field=models.CharField(db_column='Accion_Auditoria', default='MIGRACION_AUTOMATICA', max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='auditorias',
            name='datos_anteriores',
            field=models.JSONField(blank=True, db_column='Datos_Anteriores', null=True),
        ),
        migrations.AddField(
            model_name='auditorias',
            name='fh_accion',
            field=models.DateTimeField(db_column='FH_Accion', default=datetime.datetime(2025, 9, 30, 12, 30, 22, 604217, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='auditorias',
            name='id_registro',
            field=models.IntegerField(db_column='ID_Registro', default='N/A'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='auditorias',
            name='id_usuario',
            field=models.ForeignKey(blank=True, db_column='ID_Usuario', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='a_central.empleados'),
        ),
        migrations.AddField(
            model_name='auditorias',
            name='nombre_tabla',
            field=models.CharField(db_column='Nombre_Tabla', default='TABLA_DESCONOCIDA', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='empleados',
            name='apellido_emp',
            field=models.CharField(db_column='Apellido_Emp', default='SIN_APELLIDO', max_length=80),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='empleados',
            name='borrado_emp',
            field=models.BooleanField(db_column='Borrado_Emp', default=False),
        ),
        migrations.AddField(
            model_name='empleados',
            name='contrasena_emp',
            field=models.CharField(db_column='Contrasena_Emp', default='temporal123', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='empleados',
            name='dni_emp',
            field=models.BigIntegerField(db_column='DNI_Emp', default='0000', unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='empleados',
            name='domicilio_emp',
            field=models.CharField(blank=True, db_column='Domicilio_Emp', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='empleados',
            name='email_emp',
            field=models.CharField(db_column='Email_Emp', default='ejemplo@nose.com', max_length=150, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='empleados',
            name='fecha_alta_emp',
            field=models.DateField(db_column='Fecha_Alta_Emp', default=datetime.datetime(2025, 9, 30, 13, 56, 0, 955996, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='empleados',
            name='fecha_baja_emp',
            field=models.DateField(blank=True, db_column='Fecha_Baja_Emp', null=True),
        ),
        migrations.AddField(
            model_name='empleados',
            name='fh_borrado_e',
            field=models.DateTimeField(blank=True, db_column='FH_Borrado_E', null=True),
        ),
        migrations.AddField(
            model_name='empleados',
            name='id_empleado',
            field=models.AutoField(db_column='ID_Empleado', primary_key=True, serialize=False),
        ),
        migrations.AddField(
            model_name='empleados',
            name='nombre_emp',
            field=models.CharField(db_column='Nombre_Emp', default='Ezequiel', max_length=80),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='empleados',
            name='telefono_emp',
            field=models.CharField(blank=True, db_column='Telefono_Emp', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='empleados',
            name='usuario_emp',
            field=models.CharField(blank=True, db_column='Usuario_Emp', max_length=50, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='provincias',
            name='borrado_provincia',
            field=models.BooleanField(db_column='Borrado_Provincia', default=False),
        ),
        migrations.AddField(
            model_name='provincias',
            name='fh_borrado_p',
            field=models.DateTimeField(blank=True, db_column='FH_Borrado_P', null=True),
        ),
        migrations.AlterField(
            model_name='auditorias',
            name='datos_nuevos',
            field=models.JSONField(blank=True, db_column='Datos_Nuevos', null=True),
        ),
        migrations.AlterField(
            model_name='auditorias',
            name='id_auditoria',
            field=models.AutoField(db_column='ID_Auditoria', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='provincias',
            name='id_provincia',
            field=models.AutoField(db_column='ID_Provincia', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='provincias',
            name='nombre_provincia',
            field=models.CharField(db_column='Nombre_Provincia', max_length=50, unique=True),
        ),
        migrations.CreateModel(
            name='LocalesComerciales',
            fields=[
                ('id_loc_com', models.AutoField(db_column='ID_Loc_Com', primary_key=True, serialize=False)),
                ('nombre_loc_com', models.CharField(db_column='Nombre_Loc_Com', max_length=100)),
                ('cod_postal_loc_com', models.IntegerField(blank=True, db_column='Cod_Postal_Loc_Com', null=True)),
                ('telefono_loc_com', models.CharField(blank=True, db_column='Telefono_Loc_Com', max_length=30, null=True)),
                ('direccion_loc_com', models.CharField(blank=True, db_column='Direccion_Loc_Com', max_length=100, null=True)),
                ('borrado_loc_com', models.BooleanField(db_column='Borrado_Loc_Com', default=False)),
                ('fh_borrado_lc', models.DateTimeField(blank=True, db_column='FH_Borrado_LC', null=True)),
                ('id_provincia', models.ForeignKey(db_column='ID_Provincia', on_delete=django.db.models.deletion.DO_NOTHING, to='a_central.provincias')),
            ],
            options={
                'verbose_name_plural': 'Locales Comerciales',
                'db_table': 'Locales_Comerciales',
            },
        ),
        migrations.CreateModel(
            name='Empleadosxloccom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('turno_exlc', models.CharField(db_column='Turno_ExLC', max_length=20)),
                ('horas_trabajadas', models.IntegerField(db_column='Horas_Trabajadas')),
                ('id_empleado', models.ForeignKey(db_column='ID_Empleado', on_delete=django.db.models.deletion.DO_NOTHING, to='a_central.empleados')),
                ('id_loc_com', models.ForeignKey(db_column='ID_Loc_Com', on_delete=django.db.models.deletion.DO_NOTHING, to='a_central.localescomerciales')),
            ],
            options={
                'verbose_name_plural': 'Empleados por Local Comercial',
                'db_table': 'EmpleadosXLocCom',
            },
        ),
        migrations.CreateModel(
            name='Productos',
            fields=[
                ('id_producto', models.AutoField(db_column='ID_Producto', primary_key=True, serialize=False)),
                ('nombre_producto', models.CharField(blank=True, db_column='Nombre_Producto', max_length=150, null=True)),
                ('precio_unit_prod', models.DecimalField(blank=True, db_column='Precio_Unit_Prod', decimal_places=2, max_digits=10, null=True)),
                ('fecha_venc_prod', models.DateField(blank=True, db_column='Fecha_Venc_Prod', null=True)),
                ('borrado_prod', models.BooleanField(db_column='Borrado_Prod', default=False)),
                ('fh_borrado_prod', models.DateTimeField(blank=True, db_column='FH_Borrado_Prod', null=True)),
                ('id_marca', models.ForeignKey(blank=True, db_column='ID_Marca', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='a_central.marcas')),
            ],
            options={
                'verbose_name_plural': 'Productos',
                'db_table': 'Productos',
            },
        ),
        migrations.DeleteModel(
            name='Roles',
        ),
    ]
