# Generated by Django 5.2.5 on 2025-10-12 14:50

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('a_central', '0003_localescomerciales_fecha_alta_loc_com'),
    ]

    operations = [
        migrations.AddField(
            model_name='productos',
            name='fecha_alta_prod',
            field=models.DateTimeField(auto_now_add=True, db_column='Fecha_Alta_Prod', default=datetime.datetime(2025, 10, 12, 14, 50, 21, 416009, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
    ]
