# Generated by Django 5.2.5 on 2025-10-13 19:29

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('a_central', '0004_productos_fecha_alta_prod'),
    ]

    operations = [
        migrations.AlterField(
            model_name='billeterasvirtuales',
            name='fh_alta_bv',
            field=models.DateTimeField(db_column='FH_Alta_BV', default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='billeterasvirtuales',
            name='saldo_bv',
            field=models.DecimalField(db_column='Saldo_BV', decimal_places=2, default=0.0, max_digits=12),
        ),
    ]
