# Generated by Django 5.2.5 on 2025-09-30 13:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('a_cajas', '0003_alter_cajas_unique_together_cajas_borrado_caja_and_more'),
        ('a_central', '0004_billeterasvirtuales_marcas_proveedores_and_more'),
        ('a_compras', '0002_remove_compras_borrado_logico_and_more'),
        ('a_stock', '0002_remove_productos_id_marca_and_more'),
        ('a_ventas', '0002_remove_detallesventas_borrado_logico_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Sucursales',
        ),
        migrations.AlterUniqueTogether(
            name='localescomerciales',
            unique_together={('id_provincia', 'nombre_loc_com')},
        ),
        migrations.AlterUniqueTogether(
            name='empleadosxloccom',
            unique_together={('id_empleado', 'id_loc_com')},
        ),
    ]
