# Generated by Django 5.2.5 on 2025-11-10 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('a_central', '0005_alter_billeterasvirtuales_fh_alta_bv_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='productos',
            name='cantidad_por_pack',
            field=models.PositiveIntegerField(blank=True, db_column='Cantidad_Por_Pack', help_text='Solo completar si el producto viene en pack (ej. 6 latas)', null=True),
        ),
        migrations.AddField(
            model_name='productos',
            name='tipo_unidad',
            field=models.CharField(choices=[('unidad', 'Unidad'), ('pack', 'Pack'), ('kilo', 'Kilo'), ('litro', 'Litro'), ('docena', 'Docena')], db_column='Tipo_Unidad', default='unidad', max_length=20),
        ),
    ]
