# Generated by Django 5.2.5 on 2025-10-04 20:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('a_central', '0005_delete_sucursales_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='empleados',
            name='user_auth',
            field=models.OneToOneField(blank=True, db_column='ID_User_Auth', null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Usuario del Sistema de Auth'),
        ),
    ]
