# Generated by Django 5.2.5 on 2025-08-24 01:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('a_caja', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BilleterasVirtuales',
            fields=[
                ('id_bv', models.IntegerField(db_column='ID_BV', primary_key=True, serialize=False)),
                ('nombre_bv', models.CharField(blank=True, db_column='Nombre_BV', max_length=50, null=True)),
                ('usuario_bv', models.CharField(blank=True, db_column='Usuario_BV', max_length=50, null=True)),
                ('contrasena_bv', models.CharField(blank=True, db_column='Contrasena_BV', max_length=50, null=True)),
                ('cvu_bv', models.CharField(blank=True, db_column='CVU_BV', max_length=20, null=True)),
                ('fecha_alta_bv', models.DateField(blank=True, db_column='Fecha_Alta_BV', null=True)),
                ('hora_alta_bv', models.TimeField(blank=True, db_column='Hora_Alta_BV', null=True)),
                ('fecha_baja_bv', models.DateField(blank=True, db_column='Fecha_Baja_BV', null=True)),
                ('hora_baja_bv', models.TimeField(blank=True, db_column='Hora_Baja_BV', null=True)),
                ('saldo_bv', models.DecimalField(blank=True, db_column='Saldo_BV', decimal_places=2, max_digits=10, null=True)),
                ('id_cajas', models.ForeignKey(db_column='ID_Cajas', on_delete=django.db.models.deletion.DO_NOTHING, to='a_caja.cajas')),
            ],
            options={
                'db_table': 'Billeteras_Virtuales',
            },
        ),
        migrations.CreateModel(
            name='Billeteravirtualesxcajas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('veces_utilizada_compra', models.IntegerField(blank=True, db_column='Veces_Utilizada_Compra', null=True)),
                ('veces_utilizada_venta', models.IntegerField(blank=True, db_column='Veces_Utilizada_Venta', null=True)),
                ('id_bv', models.ForeignKey(db_column='ID_BV', on_delete=django.db.models.deletion.DO_NOTHING, to='a_billeteras_v.billeterasvirtuales')),
                ('id_cajas', models.ForeignKey(db_column='ID_Cajas', on_delete=django.db.models.deletion.DO_NOTHING, to='a_caja.cajas')),
            ],
            options={
                'db_table': 'BilleteraVirtualesXCajas',
                'unique_together': {('id_cajas', 'id_bv')},
            },
        ),
    ]
