# Generated by Django 5.2.5 on 2025-08-24 01:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('a_empleados', '0001_initial'),
        ('a_sucursales', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cajas',
            fields=[
                ('id_cajas', models.IntegerField(db_column='ID_Cajas', primary_key=True, serialize=False)),
                ('fecha_apertura_cj', models.DateField(blank=True, db_column='Fecha_Apertura_Cj', null=True)),
                ('hora_apertura_cj', models.TimeField(blank=True, db_column='Hora_Apertura_Cj', null=True)),
                ('fecha_cierre_cj', models.DateField(blank=True, db_column='Fecha_Cierre_Cj', null=True)),
                ('hora_cierre_cj', models.TimeField(blank=True, db_column='Hora_Cierre_Cj', null=True)),
                ('monto_inicial_cj', models.DecimalField(blank=True, db_column='Monto_Inicial_Cj', decimal_places=2, max_digits=10, null=True)),
                ('monto_final_cj', models.DecimalField(blank=True, db_column='Monto_Final_Cj', decimal_places=2, max_digits=10, null=True)),
                ('total_venta_efectivo', models.DecimalField(blank=True, db_column='Total_Venta_Efectivo', decimal_places=2, max_digits=10, null=True)),
                ('total_ventas_bv', models.DecimalField(blank=True, db_column='Total_Ventas_BV', decimal_places=2, max_digits=10, null=True)),
                ('total_egreso_efectivo', models.DecimalField(blank=True, db_column='Total_Egreso_Efectivo', decimal_places=2, max_digits=10, null=True)),
                ('total_egreso_bv', models.DecimalField(blank=True, db_column='Total_Egreso_BV', decimal_places=2, max_digits=10, null=True)),
                ('id_loc_com', models.ForeignKey(db_column='ID_Loc_Com', on_delete=django.db.models.deletion.DO_NOTHING, to='a_sucursales.localescomerciales')),
                ('legajo_nro', models.ForeignKey(db_column='Legajo_Nro', on_delete=django.db.models.deletion.DO_NOTHING, to='a_empleados.empleados')),
            ],
            options={
                'db_table': 'Cajas',
            },
        ),
        migrations.CreateModel(
            name='ReportesAperturas',
            fields=[
                ('id_ra', models.IntegerField(db_column='ID_RA', primary_key=True, serialize=False)),
                ('fecha_ra', models.DateField(blank=True, db_column='Fecha_RA', null=True)),
                ('hora_ra', models.TimeField(blank=True, db_column='Hora_RA', null=True)),
                ('monto_efectivo_ra', models.DecimalField(blank=True, db_column='Monto_Efectivo_RA', decimal_places=2, max_digits=10, null=True)),
                ('monto_bv_ra', models.DecimalField(blank=True, db_column='Monto_BV_RA', decimal_places=2, max_digits=10, null=True)),
                ('ruta_ubi_arch_ra', models.CharField(blank=True, db_column='Ruta_Ubi_Arch_RA', max_length=500, null=True)),
                ('id_cajas', models.ForeignKey(db_column='ID_Cajas', on_delete=django.db.models.deletion.DO_NOTHING, to='a_caja.cajas')),
            ],
            options={
                'db_table': 'Reportes_Aperturas',
            },
        ),
        migrations.CreateModel(
            name='ReportesCierres',
            fields=[
                ('id_rc', models.IntegerField(db_column='ID_RC', primary_key=True, serialize=False)),
                ('fecha_rc', models.DateField(blank=True, db_column='Fecha_RC', null=True)),
                ('hora_rc', models.TimeField(blank=True, db_column='Hora_RC', null=True)),
                ('monto_efectivo', models.DecimalField(blank=True, db_column='Monto_Efectivo', decimal_places=2, max_digits=10, null=True)),
                ('monto_bv', models.DecimalField(blank=True, db_column='Monto_BV', decimal_places=2, max_digits=10, null=True)),
                ('ruta_ubi_arch_rc', models.CharField(blank=True, db_column='Ruta_Ubi_Arch_RC', max_length=500, null=True)),
                ('id_cajas', models.ForeignKey(db_column='ID_Cajas', on_delete=django.db.models.deletion.DO_NOTHING, to='a_caja.cajas')),
            ],
            options={
                'db_table': 'Reportes_Cierres',
            },
        ),
    ]
