# Generated by Django 5.2.5 on 2025-10-10 20:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('a_cajas', '0001_initial'),
        ('a_central', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ventas',
            fields=[
                ('id_venta', models.AutoField(db_column='ID_Venta', primary_key=True, serialize=False)),
                ('fh_venta', models.DateTimeField(db_column='FH_Venta')),
                ('total_venta', models.DecimalField(db_column='Total_Venta', decimal_places=2, max_digits=10)),
                ('borrado_venta', models.BooleanField(db_column='Borrado_Venta', default=False)),
                ('fh_borrado_venta', models.DateTimeField(blank=True, db_column='FH_Borrado_Venta', null=True)),
                ('id_caja', models.ForeignKey(blank=True, db_column='ID_Caja', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='a_cajas.cajas', verbose_name='Caja')),
                ('id_empleado', models.ForeignKey(db_column='ID_Empleado', on_delete=django.db.models.deletion.DO_NOTHING, to='a_central.empleados', verbose_name='Empleado Vendedor')),
                ('id_loc_com', models.ForeignKey(db_column='ID_Loc_Com', on_delete=django.db.models.deletion.DO_NOTHING, to='a_central.localescomerciales', verbose_name='Local Comercial')),
            ],
            options={
                'verbose_name_plural': 'Ventas',
                'db_table': 'Ventas',
            },
        ),
        migrations.CreateModel(
            name='DetallesVentas',
            fields=[
                ('id_detalle_venta', models.AutoField(db_column='ID_Detalle_Venta', primary_key=True, serialize=False)),
                ('cantidad', models.IntegerField(db_column='Cantidad')),
                ('precio_unitario_venta', models.DecimalField(db_column='Precio_Unitario_Venta', decimal_places=2, max_digits=10)),
                ('subtotal', models.DecimalField(db_column='Subtotal', decimal_places=2, max_digits=10)),
                ('borrado_det_v', models.BooleanField(db_column='Borrado_Det_V', default=False)),
                ('fh_borrado_det_v', models.DateTimeField(blank=True, db_column='FH_Borrado_Det_V', null=True)),
                ('id_producto', models.ForeignKey(db_column='ID_Producto', on_delete=django.db.models.deletion.DO_NOTHING, to='a_central.productos')),
                ('id_venta', models.ForeignKey(db_column='ID_Venta', on_delete=django.db.models.deletion.DO_NOTHING, to='a_ventas.ventas')),
            ],
            options={
                'verbose_name_plural': 'Detalles de Ventas',
                'db_table': 'Detalles_Ventas',
                'unique_together': {('id_venta', 'id_producto')},
            },
        ),
    ]
