# Generated by Django 5.2.5 on 2025-09-13 23:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('a_cajas', '0001_initial'),
        ('a_central', '0001_initial'),
        ('a_stock', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ventas',
            fields=[
                ('id_venta', models.BigAutoField(primary_key=True, serialize=False)),
                ('fecha_hora_venta', models.DateTimeField(auto_now_add=True)),
                ('monto_total', models.DecimalField(decimal_places=2, default=0.0, max_digits=14)),
                ('situacion_venta', models.CharField(choices=[('FINALIZADO', 'FINALIZADO'), ('EN_PROCESO', 'EN_PROCESO'), ('CANCELADO', 'CANCELADO')], max_length=10)),
                ('borrado_logico', models.BooleanField(default=False)),
                ('id_caja', models.ForeignKey(db_column='id_caja', on_delete=django.db.models.deletion.CASCADE, to='a_cajas.cajas')),
                ('id_sucursal', models.ForeignKey(db_column='id_sucursal', on_delete=django.db.models.deletion.CASCADE, to='a_central.sucursales')),
                ('legajo_empleado', models.ForeignKey(db_column='legajo_empleado', on_delete=django.db.models.deletion.CASCADE, to='a_central.empleados')),
            ],
            options={
                'verbose_name_plural': 'Ventas',
                'db_table': 'Ventas',
            },
        ),
        migrations.CreateModel(
            name='DetallesVentas',
            fields=[
                ('id_detalle_venta', models.BigAutoField(primary_key=True, serialize=False)),
                ('cantidad', models.BigIntegerField()),
                ('precio_unitario', models.DecimalField(decimal_places=2, max_digits=12)),
                ('borrado_logico', models.BooleanField(default=False)),
                ('id_producto', models.ForeignKey(db_column='id_producto', on_delete=django.db.models.deletion.CASCADE, to='a_stock.productos')),
                ('id_venta', models.ForeignKey(db_column='id_venta', on_delete=django.db.models.deletion.CASCADE, to='a_ventas.ventas')),
            ],
            options={
                'verbose_name_plural': 'Detalles de Ventas',
                'db_table': 'Detalles_Ventas',
                'unique_together': {('id_venta', 'id_producto')},
            },
        ),
    ]
