# Generated by Django 5.2.5 on 2025-08-24 01:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('a_caja', '0001_initial'),
        ('a_productos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ventas',
            fields=[
                ('id_ventas', models.IntegerField(db_column='ID_Ventas', primary_key=True, serialize=False)),
                ('fecha_venta', models.DateField(blank=True, db_column='Fecha_Venta', null=True)),
                ('hora_venta', models.TimeField(blank=True, db_column='Hora_Venta', null=True)),
                ('monto_final', models.DecimalField(blank=True, db_column='Monto_Final', decimal_places=2, max_digits=10, null=True)),
                ('id_cajas', models.ForeignKey(db_column='ID_Cajas', on_delete=django.db.models.deletion.DO_NOTHING, to='a_caja.cajas')),
            ],
            options={
                'db_table': 'Ventas',
            },
        ),
        migrations.CreateModel(
            name='VentasCanceladas',
            fields=[
                ('id_vc', models.IntegerField(db_column='ID_VC', primary_key=True, serialize=False)),
                ('fecha_vc', models.DateField(blank=True, db_column='Fecha_VC', null=True)),
                ('hora_vc', models.TimeField(blank=True, db_column='Hora_VC', null=True)),
                ('monto_vc', models.DecimalField(blank=True, db_column='Monto_VC', decimal_places=2, max_digits=10, null=True)),
                ('id_cajas', models.ForeignKey(db_column='ID_Cajas', on_delete=django.db.models.deletion.DO_NOTHING, to='a_caja.cajas')),
            ],
            options={
                'db_table': 'Ventas_Canceladas',
            },
        ),
        migrations.CreateModel(
            name='DetalleVentas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad_producto', models.IntegerField(blank=True, db_column='Cantidad_Producto', null=True)),
                ('precio_unitario', models.DecimalField(blank=True, db_column='Precio_Unitario', decimal_places=2, max_digits=10, null=True)),
                ('monto_final', models.DecimalField(blank=True, db_column='Monto_Final', decimal_places=2, max_digits=10, null=True)),
                ('id_productos', models.ForeignKey(db_column='ID_Productos', on_delete=django.db.models.deletion.DO_NOTHING, to='a_productos.productos')),
                ('id_ventas', models.ForeignKey(db_column='ID_Ventas', on_delete=django.db.models.deletion.DO_NOTHING, to='a_ventas.ventas')),
            ],
            options={
                'db_table': 'Detalle_Ventas',
                'unique_together': {('id_ventas', 'id_productos')},
            },
        ),
    ]
