# Generated by Django 5.2.5 on 2025-11-23 03:08

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('a_ventas', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detallesventas',
            name='id_venta',
            field=models.ForeignKey(db_column='ID_Venta', on_delete=django.db.models.deletion.DO_NOTHING, related_name='detalles', to='a_ventas.ventas'),
        ),
        migrations.AlterField(
            model_name='ventas',
            name='fh_venta',
            field=models.DateTimeField(db_column='FH_Venta', default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='ventas',
            name='total_venta',
            field=models.DecimalField(db_column='Total_Venta', decimal_places=2, default=0, max_digits=10),
        ),
    ]
