# Generated by Django 5.2.5 on 2025-09-30 13:59

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('a_cajas', '0002_arqueoscaja_movimientosfinancieros_pagoscompras_and_more'),
        ('a_central', '0004_billeterasvirtuales_marcas_proveedores_and_more'),
        ('a_ventas', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='detallesventas',
            name='borrado_logico',
        ),
        migrations.RemoveField(
            model_name='detallesventas',
            name='precio_unitario',
        ),
        migrations.RemoveField(
            model_name='ventas',
            name='borrado_logico',
        ),
        migrations.RemoveField(
            model_name='ventas',
            name='fecha_hora_venta',
        ),
        migrations.RemoveField(
            model_name='ventas',
            name='id_sucursal',
        ),
        migrations.RemoveField(
            model_name='ventas',
            name='legajo_empleado',
        ),
        migrations.RemoveField(
            model_name='ventas',
            name='monto_total',
        ),
        migrations.RemoveField(
            model_name='ventas',
            name='situacion_venta',
        ),
        migrations.AddField(
            model_name='detallesventas',
            name='borrado_det_v',
            field=models.BooleanField(db_column='Borrado_Det_V', default=False),
        ),
        migrations.AddField(
            model_name='detallesventas',
            name='fh_borrado_det_v',
            field=models.DateTimeField(blank=True, db_column='FH_Borrado_Det_V', null=True),
        ),
        migrations.AddField(
            model_name='detallesventas',
            name='precio_unitario_venta',
            field=models.DecimalField(db_column='Precio_Unitario_Venta', decimal_places=2, default=0, max_digits=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='detallesventas',
            name='subtotal',
            field=models.DecimalField(db_column='Subtotal', decimal_places=2, default=0, max_digits=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ventas',
            name='borrado_venta',
            field=models.BooleanField(db_column='Borrado_Venta', default=False),
        ),
        migrations.AddField(
            model_name='ventas',
            name='fh_borrado_venta',
            field=models.DateTimeField(blank=True, db_column='FH_Borrado_Venta', null=True),
        ),
        migrations.AddField(
            model_name='ventas',
            name='fh_venta',
            field=models.DateTimeField(db_column='FH_Venta', default=datetime.datetime(2025, 9, 30, 13, 57, 55, 59192, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ventas',
            name='id_empleado',
            field=models.ForeignKey(db_column='ID_Empleado', default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='a_central.empleados', verbose_name='Empleado Vendedor'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ventas',
            name='id_loc_com',
            field=models.ForeignKey(db_column='ID_Loc_Com', default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='a_central.localescomerciales', verbose_name='Local Comercial'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ventas',
            name='total_venta',
            field=models.DecimalField(db_column='Total_Venta', decimal_places=2, default=1, max_digits=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='detallesventas',
            name='cantidad',
            field=models.IntegerField(db_column='Cantidad'),
        ),
        migrations.AlterField(
            model_name='detallesventas',
            name='id_detalle_venta',
            field=models.AutoField(db_column='ID_Detalle_Venta', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='detallesventas',
            name='id_producto',
            field=models.ForeignKey(db_column='ID_Producto', on_delete=django.db.models.deletion.DO_NOTHING, to='a_central.productos'),
        ),
        migrations.AlterField(
            model_name='detallesventas',
            name='id_venta',
            field=models.ForeignKey(db_column='ID_Venta', on_delete=django.db.models.deletion.DO_NOTHING, to='a_ventas.ventas'),
        ),
        migrations.AlterField(
            model_name='ventas',
            name='id_caja',
            field=models.ForeignKey(blank=True, db_column='ID_Caja', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='a_cajas.cajas', verbose_name='Caja'),
        ),
        migrations.AlterField(
            model_name='ventas',
            name='id_venta',
            field=models.AutoField(db_column='ID_Venta', primary_key=True, serialize=False),
        ),
    ]
