# Generated by Django 5.2.5 on 2025-08-24 01:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('a_sucursales', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Productos',
            fields=[
                ('id_productos', models.IntegerField(db_column='ID_Productos', primary_key=True, serialize=False)),
                ('nombre_producto', models.CharField(blank=True, db_column='Nombre_Producto', max_length=50, null=True)),
                ('precio_unitario', models.DecimalField(blank=True, db_column='Precio_Unitario', decimal_places=2, max_digits=10, null=True)),
                ('fecha_elaboracion', models.DateField(blank=True, db_column='Fecha_Elaboracion', null=True)),
                ('fecha_vencimiento', models.DateField(blank=True, db_column='Fecha_Vencimiento', null=True)),
                ('cant_stock', models.IntegerField(blank=True, db_column='Cant_Stock', null=True)),
            ],
            options={
                'db_table': 'Productos',
            },
        ),
        migrations.CreateModel(
            name='ReportesStock',
            fields=[
                ('id_rst', models.IntegerField(db_column='ID_RST', primary_key=True, serialize=False)),
                ('fecha_rs', models.DateField(blank=True, db_column='Fecha_RS', null=True)),
                ('hora_rs', models.TimeField(blank=True, db_column='Hora_RS', null=True)),
                ('ruta_ubi_arch_rs', models.CharField(blank=True, db_column='Ruta_Ubi_Arch_RS', max_length=500, null=True)),
                ('descripcion', models.CharField(blank=True, db_column='Descripcion', max_length=100, null=True)),
                ('id_productos', models.ForeignKey(db_column='ID_Productos', on_delete=django.db.models.deletion.DO_NOTHING, to='a_productos.productos')),
            ],
            options={
                'db_table': 'Reportes_Stock',
            },
        ),
        migrations.CreateModel(
            name='Productoxloccom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('observaciones', models.CharField(blank=True, db_column='Observaciones', max_length=100, null=True)),
                ('id_loc_com', models.ForeignKey(db_column='ID_Loc_Com', on_delete=django.db.models.deletion.DO_NOTHING, to='a_sucursales.localescomerciales')),
                ('id_productos', models.ForeignKey(db_column='ID_Productos', on_delete=django.db.models.deletion.DO_NOTHING, to='a_productos.productos')),
            ],
            options={
                'db_table': 'ProductoXLocCom',
                'unique_together': {('id_productos', 'id_loc_com')},
            },
        ),
    ]
