# Generated by Django 5.2.5 on 2025-08-25 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('a_productos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='productos',
            name='borrado_logico',
            field=models.BooleanField(default=True),
        ),
    ]
